- frontend/src/app/settings/admin-settings/admin-user-settings/admin-user-settings.component.ts
This PR fixes the problem that during search for specific users they were not suggested if theirs names contained capital letters. 
It may also fix #45.
> frontend-settings: improve user search

- backend/t4cclient/core/authentication/database/__init__.py
- backend/t4cclient/routes/repositories/users.py
- frontend/.gitignore
This PR fixes #19. In the `backend` function `add_user_to_repository` it is checked that an user is not added a second time. Otherwise a `HTTPException` is raised.
> Validate in backend that an user is not added twice 

- CONTRIBUTING.md
- backend/setup.cfg
- backend/t4cclient/config/__init__.py
- backend/t4cclient/config/diff.py
- backend/t4cclient/config/loader.py
Our configuration file changes pretty often, e.g. when introducing new configuration values.
We require the users to have an up to date configuration file.
In the usual workflow, it is hard to see if a value or key changed in the template.
This PR automates the comparision.
A developer can now see directly when a value is changed by running `python -m t4cclient.config.diff`
> Add configuration diff

- backend/t4cclient/__main__.py
- backend/t4cclient/alembic/env.py
- backend/t4cclient/extensions/backups/ease/__init__.py
- backend/t4cclient/extensions/backups/jenkins/__init__.py
- backend/t4cclient/extensions/modelsources/git/__init__.py
- backend/t4cclient/extensions/modelsources/t4c/__init__.py
- backend/t4cclient/routes/repositories/__init__.py
- backend/t4cclient/sql_models/extensions.py
alembic didn't find the models, because they were not loaded corretly in the `env.py`.
Also, the new extensions were not loaded correctly.
The way of loading resulted in a circular import, because for each extension all submodules were loaded.
This is now fixed.
> Rework modelloading

- backend/.dockerignore
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/app.module.ts
- frontend/src/app/settings/admin-settings/admin-user-settings/admin-user-settings.component.css
- frontend/src/app/settings/admin-settings/admin-user-settings/admin-user-settings.component.html
- frontend/src/app/settings/repository-manager-settings/repository-settings/repository-user-settings/repository-user-settings.component.css
- frontend/src/app/settings/repository-manager-settings/repository-settings/repository-user-settings/repository-user-settings.component.html
- frontend/src/custom-theme.scss
The ngx-simplebar wrapper was removed from the project and its two occurrences were replaced. Now it uses .simple-scroll class and relies on ::webkit-scrollbar for the style. The new style is accessible with the .simple-scroll class for all scrollable blocks.
There is no transition between the normal and hovered effect, as it's not possible without ~~a sorcery~~ a significant complexity overhead that for the sake of reusability I prefer not using.
Resolves #83
> Replace ngx simplebar

- CONTRIBUTING.md
This PR adds the instructions to launch a t4cserver in the CONTRIBUTING file, and specify that the cluster must be runned to use Guacamole.
Please @jamilraichouni follow this tutorial to be sure that the good instructions are provided.
> Add t4c server mock in documentation

- frontend/src/app/auth/auth-redirect/auth-redirect.component.ts
- frontend/src/app/auth/auth/auth.component.css
- frontend/src/app/auth/auth/auth.component.html
- frontend/src/app/auth/auth/auth.component.ts
When the OAuth2 redirects to the callback with an error, the user is redirected to the login page, and is shown an error message. The parameters taken in account are _error_, _error_description_ and _error_uri_, as specified in [the OAuth2 specification](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2).
Resolves #65
Following [this link](http://localhost:4200/oauth2/callback?error=access_denied&error_description=OAuth2%20token%20access%20for%20this%20resource%20is%20prohibited.&error_uri=https:%2F%2Fmock.oauth.de%2Faccess_denied%0D%0A) should redirect to the login page and show an error message containing the error, its description (if any) and its uri (if any)
> handling oauth errors

- frontend/src/app/session-overview/session-overview.component.css
- frontend/src/app/session-overview/session-overview.component.html
- frontend/src/app/session-overview/session-overview.component.ts
In the session overview, administrators can now select specific sessions and terminate them all together.
A new checkbox "Select all sessions" has been added. The checkbox is disabled if no session exists. The checkbox is selected if exactly all sessions are selected. If all sessions are selected, you can deselect all sessions by deselecting the checkbox.
> Rework session overview

- backend/config/config_template.yaml
- backend/t4cclient/core/authentication/database/__init__.py
- backend/t4cclient/extensions/backups/ease/routes.py
- backend/t4cclient/extensions/modelsources/t4c/connection.py
- backend/t4cclient/routes/repositories/__init__.py
- backend/t4cclient/routes/repositories/users.py
- mocks/t4c-server/mock/users.py
This PR relates to issue #36. Here, application admins are set by default as t4c repository admins during project creation.
> Set admins by default as t4c-repository-admins during project creation

- frontend/src/app/services/auth/auth.service.ts
* This commit should've been part of #234. httpOnly cookies can't be set from Javascript.
Try open Prometheus as admin.
> Do not set cookie as HTTP only

- Makefile
In newer versions of kubectl account tokens are no longer auto-generate for ServiceAccounts. Therefore, make dashboard just outputs an empty token for those versions. This PR fixes this and should be backwards compatible, so also support older kubectl versions
> fix: update kubernetes dashboard token generation

- README.md
see commit msg
Using the (n)vim [MarkdownPreview plugin](https://github.com/iamcco/markdown-preview.nvim)
> dics: Fix broken hyperlink to license file

- Makefile
- backend/capellacollab/extensions/modelsources/t4c/connection.py
- backend/capellacollab/sessions/routes.py
- frontend/.gitignore
- frontend/package.json
- frontend/src/environments/environment.dev.ts
- frontend/src/proxy.conf.js
- helm/config/backend.yaml
Some improvements to the deployment process. I experienced timeouts when deploying a fresh copy of the collab manager.
Chore: fix missing variables in session routes.
Allow to run frontend locally with requests proxied to a deployed cluster. This allows us to have all functionality of collab-manager exposed while developing locally.
> K3d deployment and workflow improvements

- backend/capellacollab/core/authentication/database/__init__.py
- frontend/src/app/projects/create-project/create-project.component.html
- frontend/src/app/projects/create-project/create-project.component.ts
- frontend/src/app/projects/models/choose-init/choose-init.component.html
- frontend/src/app/projects/models/choose-init/choose-init.component.ts
- frontend/src/app/projects/models/choose-source/choose-source.component.html
- frontend/src/app/projects/models/choose-source/choose-source.component.ts
- frontend/src/app/projects/models/create-model/create-model.component.html
- frontend/src/app/projects/models/create-model/create-model.component.ts
- frontend/src/app/projects/models/init-model/init-model.component.html
- frontend/src/app/projects/models/init-model/init-model.component.ts
- Allow to abort a running model creation during the project creation. 
- Redirect to project after model creation when called from the project creation context. 
- Some small fixes.
#264 has a higher importance, this PR can be reviewed after #264.
> Allow to abort a running model creation

- helm/Chart.yaml
This renames the helm chart to `collab-manager`, which is the name of the platform for a while now. I don't expect any breaking changes. There were no issues when upgrading a existing application with the old name.
> Rename helm chart

- backend/capellacollab/core/authentication/database/__init__.py
- backend/capellacollab/core/authentication/database/git_models.py
- backend/capellacollab/core/authentication/responses.py
- backend/capellacollab/core/services/repositories.py
- backend/capellacollab/extensions/backups/ease/routes.py
- backend/capellacollab/extensions/modelsources/git/routes.py
- backend/capellacollab/projects/capellamodels/routes.py
- backend/capellacollab/projects/routes.py
- backend/capellacollab/projects/users/crud.py
- backend/capellacollab/projects/users/models.py
- backend/capellacollab/projects/users/routes.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/users/routes.py
- backend/tests/test_projects_routes.py
In v1, repositories had another meaning than in v2 and the repositories in v1 are now called projects in v2. Therefore, we need to rename all references.
> Rename legacy repositories to projects

- helm/templates/routing/nginx.ingress.yaml
We got many reports that performance is degraded when using Guacamole to connect to the session containers (e.g. #122). 
This PR adds annotations to the nginx ingress to disable proxy buffering. 
For deployments using OpenShits routes, there doesn't seem to be a good solution - I didn't find a configuration option to disable buffering for [HAProxy](http://www.haproxy.org/). When the changes from this PR have an effect, we should recommend using Ingress instead of Routes on OpenShift clusters.
> Disable proxy buffering for ingress

- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/sessions.py
- frontend/src/app/services/session/session.service.ts
- frontend/src/app/sessions/active-sessions/active-sessions.component.html
This PR fixes the issue with "Unknown" session states. Usually, we fetch the events from kubernetes to determine a detailed state for a Pod. With events, we can get information like "Image pull failed", etc. 
However, events are only stored for a limited time. Therefore, after a specific time, the sessions goes into state "unknown".
I added a fallback to the Pod phase, which should be set always: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
It has less information (e.g. just "Failed", not the reason for the failure), but it's better than nothing and should be pretty stable.
> Fix unknown state in sessions

- backend/capellacollab/projects/routes.py
- backend/capellacollab/users/injectables.py
Fix project creation: Use user id instead of username.
> fix: Use user ID for project creation

- frontend/.eslintrc.js
- frontend/src/app/general/auth/http-interceptor/auth.interceptor.ts
- frontend/src/app/helpers/skeleton-loaders/mat-card-overview-loader/mat-card-overview-loader.component.ts
This adds a rule to es-lint that checks if the code does not contain any console.log statements, and removes any existing `console.log`.
> Add no-console lint rule

- .pre-commit-config.yaml
- frontend/.eslintrc.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/general/auth/http-interceptor/auth.interceptor.ts
- frontend/src/app/services/auth/auth.service.ts
- frontend/src/app/services/modelsources/git-model/git-model.service.ts
This PR adds the es-lint deprecation rule and fixes all existing deprecation problems.
Resolves #322
> Add ESlint deprecation rule

- .gitignore
- backend/capellacollab/alembic/versions/9a1e6729858b_introduce_protocol_on_instance.py
- backend/capellacollab/projects/capellamodels/models.py
- backend/capellacollab/projects/capellamodels/modelsources/t4c/models.py
- backend/capellacollab/projects/models.py
- backend/capellacollab/projects/users/models.py
- backend/capellacollab/sessions/operators/abc.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/sessions/schema.py
- backend/capellacollab/settings/modelsources/t4c/models.py
- backend/capellacollab/settings/modelsources/t4c/repositories/crud.py
- backend/capellacollab/settings/modelsources/t4c/repositories/models.py
- backend/tests/test_sessions_routes.py
- frontend/src/app/services/session/session.service.ts
- frontend/src/app/services/settings/t4c-instance.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.css
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.html
- frontend/src/styles.css
This PR allows to launch a persistent session with either
- All the T4C repositories of the projects where the user has write permission
- All the T4C repositories if the user is an admin
> Persistent sessions for multiple T4C Instances

- backend/capellacollab/alembic/versions/7617cde6fbb1_link_sessions_to_projects.py
- backend/capellacollab/alembic/versions/ab01ad045341_add_readonly_docker_image.py
- backend/capellacollab/core/database/migration.py
- backend/capellacollab/projects/capellamodels/crud.py
- backend/capellacollab/projects/models.py
- backend/capellacollab/projects/routes.py
- backend/capellacollab/sessions/models.py
- backend/capellacollab/sessions/operators/abc.py
- backend/capellacollab/sessions/operators/docker.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/sessions/schema.py
- backend/capellacollab/tools/crud.py
- backend/capellacollab/tools/models.py
- backend/tests/test_sessions_routes.py
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.css
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.html
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.ts
- frontend/src/app/services/model/model.service.ts
- frontend/src/app/services/session/session.service.ts
- frontend/src/app/sessions/active-sessions/active-sessions.component.css
- frontend/src/app/sessions/active-sessions/active-sessions.component.ts
- frontend/src/app/workspaces/home.component.html
* A button to start a new read-only session is placed in the model card
* The button will load all models that match the project and tool (version) of the loaded model
NB. Read-only models only apply to models available from a git repository.
Resolves #issue
* Backend is working with limitations. It works only with one model: the first model that matches the requested tool/version.
* The frontend is working with fixed data: project is "default" and the tool is Capella 5.2.
What needs to be done still:
> Support read-only sessions

- backend/capellacollab/settings/modelsources/git/askpass.py
Askpass was not taken in account because it’s shebang contained `python` instead of `python3`. I also needed to make it executable
> Solve askpass issues

- frontend/.eslintrc.js
- frontend/src/app/services/modelsources/t4c-model/t4c-model.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.ts
This adds an es-lint rule prohibiting relative imports with a depth of three or more, and fixes existing problems with relative imports.
Resolves #371
> Add no relative import eslint rule

- helm/templates/backend/postgres.volume.yaml
- helm/templates/guacamole/postgres.volume.yaml
- helm/values.yaml
The `storageClassName` was missing in the `values.yaml` template. It was leading to unintended helm behavior (the user was not able to define the storageClassName)
> Move storageClassName to cluster config

- backend/capellacollab/settings/modelsources/git/models.py
Creating instances was not working with the migration script. This is a fix.
> Git types matches now the database structure

- backend/capellacollab/sessions/routes.py
- backend/capellacollab/sessions/schema.py
- backend/capellacollab/sessions/sessions.py
- backend/capellacollab/tools/models.py
- frontend/src/app/schemes.ts
- frontend/src/app/sessions/active-sessions/active-sessions.component.html
- frontend/src/app/sessions/delete-session-dialog/delete-session-dialog.component.html
- frontend/src/app/sessions/session-overview/session-overview.component.html
- frontend/src/app/sessions/session-overview/session-overview.component.ts
- frontend/src/app/settings/core/tools-settings/tool.service.ts
Read-only sessions were not displayed properly, with this comment, project and tool information is displayed in the frontend ("Own sessions" and "Overview").
> feat: Display read-only session metadata properly

- backend/capellacollab/settings/modelsources/t4c/repositories/interface.py
TeamForCapella repositories were created without authentication per default. This PR fixes the issue.
> Hotfix authentication

- backend/pyproject.toml
I'm using Python 3.11 by default (Fedora 37). It would be cool if the collab manager would allow that version too.
Resolves #issue
> Support Python 3.11

- Makefile
- README.md
Build multiple capella versions as part of the local deployment. 
* Update capella-dockerimages to the latest version.
* Update Makefile to work with the latest version of capella-dockerimages.
* Align naming with what's found in capella-dockerimages.
* Use standard capella images (not t4c/client), since those are built as part of `make deploy` (the new user experience)
Clean everything, including docker registry. Rebuild everything and start capella 6.0 through the collab manager
> Build and use multiple capella versions

- backend/Dockerfile
This PR removes the *kubernetes-client* and *docker.io* from the installed packages because they are not needed and the *kubernetes-client* produced errors when creating the images.
> Fix backend dockerfile

- backend/capellacollab/users/crud.py
- frontend/src/app/projects/project-detail/project-users/project-user-settings.component.ts
This PR ensures that the project user search ignores uppercase letters. More precisely, so far `toLowerCaser()` was only applied to the search string and was missing for the username, which this PR adds. In addition, this PR fixes an issue where it is currently not possible to delete a user.
Resolves #45 
Create a user named `Test@web.de`, add this user to the *default* project and then search for `test`.
> Fix user search

- backend/capellacollab/__main__.py
- backend/capellacollab/core/database/migration.py
- backend/capellacollab/settings/modelsources/t4c/repositories/interface.py
- backend/tests/conftest.py
- backend/tests/test_alembic.py
SQLAlchemy replaces special characters.
They can not be read again via engine.url, because they are escaped.
> Support postgres URLs with special characters

- backend/capellacollab/sessions/idletimeout.py
This PR fixes the problem that you can't exit the Backed with `CTRL + C`.
> Stopping the session loop when exited

- backend/capellacollab/projects/crud.py
- backend/capellacollab/projects/models.py
- backend/capellacollab/projects/routes.py
- frontend/src/app/projects/create-project/create-project.component.ts
- frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.html
- frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.ts
- frontend/src/app/services/project/project.service.spec.ts
- frontend/src/app/services/project/project.service.ts
Projects can now be renamed. The slug stays unchanged.
Resolves #396
> Introduce project renaming

- backend/capellacollab/settings/modelsources/t4c/routes.py
- frontend/src/app/helpers/skeleton-loaders/mat-card-overview-loader/mat-card-overview-loader.component.ts
- frontend/src/app/projects/models/add-git-source/add-git-source.component.ts
- frontend/src/app/projects/models/backup-settings/create-backup/create-backup.component.ts
- frontend/src/app/projects/models/model-detail/model-detail.component.css
- frontend/src/app/projects/models/model-detail/model-detail.component.html
- frontend/src/app/projects/models/model-detail/model-detail.component.ts
- frontend/src/app/projects/project-detail/model-overview/model-detail/git-model.service.ts
- frontend/src/app/services/modelsources/t4c-model/t4c-model.service.ts
- frontend/src/app/services/settings/t4c-instance.service.ts
In the Git and T4C model overview, the loading of models is not done properly. The Git models and T4C models are only reset when there is a new update from the backend. When switching between the view fast enough, you can see Git and T4C models from other tool models. This PR fixes this behaviour and adds the skeleton loader.
> Fix loading of git and t4c models

- backend/capellacollab/projects/toolmodels/backups/crud.py
- backend/capellacollab/projects/toolmodels/modelsources/git/crud.py
- backend/capellacollab/projects/toolmodels/modelsources/git/routes.py
- frontend/src/app/projects/models/add-git-source/add-git-source.component.css
- frontend/src/app/projects/models/add-git-source/add-git-source.component.html
- frontend/src/app/projects/models/add-git-source/add-git-source.component.ts
- frontend/src/app/projects/project-detail/model-overview/model-detail/git-model.service.ts
- frontend/src/environments/environment.dev.ts
Add a delete button to a git model. Deletion has to be confirmed (a simple `confirm()`) and a toaster is shown with the final result.
Resolves part of #24
> Delete git model

- backend/capellacollab/settings/modelsources/git/core.py
Otherwise, important env variables like proxy are not used
> Use system environment when running ls-remote

- backend/capellacollab/projects/toolmodels/backups/core.py
This PR fixes the problem that for capella 6.0.0 our backups stopped working. This is done by statically setting the backup connection type to `telnet` and setting `ENABLED_CDO` to `true` for the t4c server. In a follow-up PR, we should change the connection type to `http` for capella 6.x.x, since `telnet` is deprecated (as described in #485).
This PR must first be merged with https://github.com/DSD-DBS/capella-dockerimages/pull/82 and the `ENABLED_CDO` flag for the t4c server must be set to `true`.
> Add connection type for backup containers

- backend/capellacollab/projects/toolmodels/backups/crud.py
- backend/capellacollab/projects/toolmodels/modelsources/git/crud.py
- backend/capellacollab/projects/toolmodels/modelsources/t4c/crud.py
- backend/capellacollab/projects/toolmodels/modelsources/t4c/routes.py
- frontend/src/app/projects/models/model-source/t4c/manage-t4c-model/manage-t4c-model.component.html
- frontend/src/app/projects/models/model-source/t4c/manage-t4c-model/manage-t4c-model.component.ts
- frontend/src/app/projects/models/model-source/t4c/service/t4c-model.service.ts
Add a "Unlink" button to remove a T4C model.
There is already a backend route to _delete_ a t4c model. I left that untouched.
I could not test this completely, since I have no running T4C server.
> Allow deletion of t4c models from the frontend

- backend/capellacollab/core/authentication/provider/oauth/flow.py
When the access token is expired, the client sends a request to the backend to renew it with the renew token. However, if the renew token is expired as well, the backend sends an unauthenticated response. That has changed, before it was an internal server error. The frontend reacts to the "Unauthenticated" by sending a request to renew the access token again... Which leads to an infinite loop and our users are basically spamming the backend with requests.
> Remove infinite loop during authentication

- .gitignore
- README.md
- helm/Chart.lock
- helm/Chart.lock.license
With Helm 3.5 it's not possible to deploy the Collab Manager helm chart, since we now have a dependency on the Loki chart from Bitnami.
* Updated minimal required version to 3.9.x
* Check in the `Chart.lock` file, so we know which version we're deploying
> Helm version update

- helm/config/nginx-grafana.conf
- helm/templates/grafana/grafana.configmap.yaml
This eliminates the need to enter login credentials for Grafana, since we already use an authenticated proxy
Resolves #505
> Add automatic login for grafana

- Makefile
- guacamole/Dockerfile
- helm/templates/guacamole/guacamole.deployment.yaml
There was a weird behaviour that Guacamole used `/etc/guacamole` as home directory, which used the wrong `guacamole.properties`. As result, the postgres authentication module was not loaded. This was caused by an issue with the Java handling of the system variable user.home if the user doesn't exist (it was evaluated to `?`).
> Fix Guacamole authentication issue

- backend/tests/test_event_creation.py
The pytest was failing when the user's config contained a different inital admin than `your-username`.
> Use username from config instead of `your-username` in tests

- backend/pyproject.toml
We don't have support for SQLAlchemy 2.x.x yet.
> Use SQLAlchemy v1.4.x

- frontend/src/app/general/metadata/version/version.component.ts
- frontend/src/app/projects/models/backup-settings/trigger-pipeline/trigger-pipeline.component.html
This PR fixes a minor issue that `lastrun` is undefined after a backup is created and never run. In that case, selecting this pipeline resulted in an error in the console. In addition, this PR adds a `v` in front of the backend version displayed in the frontend to make it consistent with the other versions displayed.
> Fix lastrun possible null after backups creation

- backend/capellacollab/core/logging.py
This commit also prints all messages with LEVEL >= INFO for the healthcheck route. This is particually interesting because we're not able to filter for extra arguments in the logging filter as `logging.LogRecord` doesn't contain extra attributes. Therefore, we're just filtering for the message. The filtering is more specific now, it also checks for the `path=` prefix.
> Print errors in `/healthcheck`

- .github/CODEOWNERS
When two CODEOWNERS are created and one CODEOWNER opens a PR, the merge is blocked until the second CODEOWNER approves. This is not the wanted workflow - PRs from the main CODEOWNER shouldn't require a review from another CODEOWNER.
> Remove @vik378 from CODEOWNERS

- backend/Makefile
- frontend/src/app/sessions/session-overview/session-overview.component.html
This PR includes showing the tool + version also for persistent sessions in the session overview. Since the tool and version are already written into the database the only change need for this was to remove a condition in the `session-overview.component.html`.
Solves #446
> Add tool to persistent sessions in session overview

- frontend/src/app/settings/modelsources/git-settings/edit-git-settings/edit-git-settings.component.html
- frontend/src/app/settings/modelsources/git-settings/edit-git-settings/edit-git-settings.component.ts
- frontend/src/app/settings/modelsources/git-settings/git-settings.component.html
- frontend/src/app/settings/modelsources/git-settings/git-settings.component.ts
- frontend/src/app/settings/modelsources/git-settings/service/git-instances.service.ts
This PR first simplifies the settings component and in addition adds a name validation for the edit git instance component (until now we could actually have two instances with the same name)
> Simplify git settings component

- backend/capellacollab/core/database/migration.py
- backend/capellacollab/projects/toolmodels/crud.py
- backend/capellacollab/projects/toolmodels/routes.py
- backend/capellacollab/tools/crud.py
- backend/tests/test_sessions_routes.py
- backend/tests/toolmodels/conftest.py
This PR adds the melody test models from the py-capellambse repository to the default project (in case of an empty database).
In addition, it includes a small fix solving #641
> Extend project initialization

- frontend/src/app/projects/project-detail/model-overview/model-complexity-badge/model-complexity-badge.component.ts
A small fix which makes the docsURL environment optional. In addition, it adds a trailing slash to the docs, otherwise it doesn't load.
> fix(frontend): Make docsURL optional in env

- backend/capellacollab/__main__.py
- backend/capellacollab/sessions/crud.py
- backend/capellacollab/sessions/metrics.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/pyproject.toml
- backend/tests/test_metrics.py
- helm/templates/backend/backend.service.yaml
- helm/templates/prometheus/prometheus.configmap.yaml
- helm/templates/prometheus/prometheus.service.yaml
- helm/templates/prometheus/prometheus.serviceaccount.yaml
Add monitoring for the backend.
The idea is that the backend can provide metrics regarding running sessions, and the session (deployment) state.
* `backend_database_sessions` (gauge) shows the number of sessions registered in our backend database
* `backend_deployed_sessions{state}` (gauge) shows the number of pods deployed in the sessions namespace, with their state
* `backend_sessions_started` (counter) total number of sessions started since application startup
* `backend_sessions_killed` (counter) total number of sessions terminated, either by user or timeout
* `starlette_*` HTTP request metrics: requests, responses, request times, exceptions, requests in progress
> Monitor our backend (web) server and deployed sessions

- backend/pyproject.toml
The alembic update contained breaking changes.
We should manually update the library in the future. https://github.com/sqlalchemy/alembic/issues/1243
> Use static version for alembic

- frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.ts
Currently, when changing the tool for requesting a readonly session from the project detail view, the tool version was not reset on a tool change. As a result, you were still able to click on "Request a ..." even though you have changed the tool and no tool version was selected. This fix simply sets the versions' form value to null in case of a tool change, invalidating the form (as the version is required), and therefore, disabling the button.
> Fix: Set tool version to null on tool change

- helm/config/backend.yaml
`ingressClassName` is [not a toplevel property](https://github.com/DSD-DBS/capella-collab-manager/blob/main/helm/values.yaml#L201).
> fix: Use ingress class name from the config correctly

- helm/values.yaml
- mocks/oauth/Makefile
The OAuth mock can sometimes be really unstable. Let's hope that the new version makes it better. 
One huge advantage is arm64 support.
Should also increase stability during the onboarding, related to #745
> Bump OAuth mock version

- backend/capellacollab/settings/modelsources/t4c/crud.py
- backend/tests/settings/test_t4c_instances.py
- frontend/src/app/projects/models/backup-settings/create-backup/create-backup.component.html
- frontend/src/app/projects/models/backup-settings/create-backup/create-backup.component.ts
- frontend/src/app/projects/models/model-detail/model-detail.component.html
- frontend/src/app/projects/models/model-detail/model-detail.component.ts
- frontend/src/app/projects/models/model-detail/t4c-model-wrapper/t4c-model-wrapper.component.ts
- frontend/src/app/projects/models/model-source/t4c/manage-t4c-model/manage-t4c-model.component.html
- frontend/src/app/projects/models/model-source/t4c/manage-t4c-model/manage-t4c-model.component.ts
- frontend/src/app/projects/models/model-source/t4c/service/t4c-model.service.ts
- frontend/src/app/projects/models/model-wrapper/model-wrapper.component.ts
- frontend/src/app/projects/project-detail/model-overview/model-detail/git-model.service.ts
- frontend/src/app/services/settings/t4c-instance.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/service/t4c-repos/t4c-repo.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.html
- frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.html
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.ts
This PR simplifies the logic within the t4c model, t4c repository and t4c instance services by moving it from components to services. This change is significant as it reduces the complexity of the components, making the code easier to maintain and read. 
**Main changes include:**
- Adoption of the BehaviourSubject workflow within services.
- Reduction of reliance on rxjs within components.
- Removal of complex constructs such as `switchMaps`.
Through these changes, we've made the code more maintainable and readable, enhancing overall code quality.
> Refactor: Simplify t4c services and enhance code maintainability

- helm/templates/backend/backend.deployment.yaml
- helm/templates/frontend/frontend.deployment.yaml
- helm/templates/grafana/grafana.deployment.yaml
- helm/templates/guacamole/guacamole.deployment.yaml
- helm/templates/guacamole/guacd.deployment.yaml
- helm/templates/prometheus/prometheus.deployment.yaml
- helm/values.yaml
Grafana stopped working with version 10.0.0 in our setup. It is producing TOO_MANY_REDIRECTS errors and sometimes redirects to "http://localhost:8080/grafana".
Until we found the root cause, we'll downgrade the version as a quick-fix.
Resolves #804
> fix: Temporarily downgrade Grafana to version 9.5.5

- Makefile
- backend/capellacollab/core/database/migration.py
- backend/capellacollab/projects/toolmodels/backups/routes.py
- backend/capellacollab/projects/toolmodels/backups/runs/interface.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/tests/projects/toolmodels/pipelines/test_pipelines.py
- backend/tests/sessions/test_sessions_routes.py
This allows jobs to work with the new consolidated t4c/client image.
To improve maintainability I changed calls to `_create_job_spec` to
named arguments.
I decided to provide the command to the k8s api, instead of hard-coding
it there, to keep the symantics of the methods used --
`create_(cron)job()` -- agnostic.
The changes should be compatible with older t4c backup images, since
they just ignore the command (args).
This PR bulds on https://github.com/DSD-DBS/capella-dockerimages/pull/162
> Use new-style t4c/client backup functionality

- guacamole/Dockerfile
- helm/values.yaml
The current Guacamole version seems to be unstable. There are two new minor versions since 1.5.2 and we should install them.
> Guacamole version update

- backend/capellacollab/sessions/operators/k8s.py
- backend/tests/sessions/test_session_operator_k8s.py
Due to an incomplete change, pipeline jobs cannot be created in the latest version of Collab manager.
This PR fixes the regression.
> Fix pipeline job

- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.ts
This saves selecting the recommended version by hand.
This fulfills #628 in a minimal way: no need for cookie or local storage.
Also, by selecting the recommended tool by default we nudge users into using those over older versions.
> feat: automatically select the recommended tool version

- backend/tests/sessions/test_session_operator_k8s.py
The K8S operator class has been improved, so we can run those tests as well.
> chore: Enable remaining k8s tests

- .gitignore
- backend/.gitignore
- backend/capellacollab/alembic/versions/3442c1b545e3_add_http_port_to_t4c_instance.py
- backend/capellacollab/projects/toolmodels/backups/core.py
- backend/capellacollab/projects/toolmodels/backups/runs/injectables.py
- backend/capellacollab/projects/toolmodels/backups/runs/routes.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/settings/modelsources/t4c/models.py
- backend/tests/projects/toolmodels/pipelines/pipeline-runs/test_pipeline_runs.py
- frontend/src/app/services/settings/t4c-instance.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.css
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/service/t4c-repos/t4c-repo.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.css
- frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.html
- frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.html
This PR includes two main things:
1. It adds a new field to our t4c instances, the `http_port`. This port is used as the port when using the *ws* protocol and when set, we also use the http method of t4c for our backups. Therefore, it is **important** to carefully check whether the `HTTP_PASSWORD` is correctly masked in the logs before deploying to production
2. Rework of the repository list: Up to now, we had to click on a repository and then scroll down to be able to delete, start, stop, or recreate a repository. This PR applys the new style where each element has its own buttons. By doing so, we also decrease the code complexity as we do not have to maintain a `selectedRepository` anymore.
Resolves #485 #596 #759
> Feat add t4c http ws port

- backend/capellacollab/projects/toolmodels/backups/core.py
Our backup image defauls to the HTTP connection method for all Capella versions >= 6.0.0.
However, the Collaboration Manager is not passing the HTTP_PORT, HTTP_USERNAME and HTTP_PASSWORD variables when the http port in not set on corresponding TeamForCapella instance.
If the HTTP port is not set, we should fall back to the telnet connection method.
Therefore, we're now passing the CONNECTION_TYPE variable explicitly.
> fix: Failing backups for Capella >= 6.0.0 without HTTP port

- backend/pyproject.toml
In fastapi version 0.100.0 pydantic v2 where introduced. Even though there shouldn't be that many breaking changes, when running `make deploy` locally I get the following error: `AttributeError: module 'pydantic._migration' has no attribute 'GenericModel'`. This PR resolves this for the moment by setting the fastapi version to `<0.100.0`.
Migration to pydantic v2 is tracked in #833
> Fix: Set fastapi version to `<0.100.0`

- backend/capellacollab/__main__.py
- backend/capellacollab/health/routes.py
- backend/capellacollab/projects/toolmodels/diagrams/routes.py
- backend/capellacollab/projects/toolmodels/diagrams/validation.py
- backend/capellacollab/projects/toolmodels/modelbadge/routes.py
- backend/capellacollab/projects/toolmodels/modelbadge/validation.py
- backend/capellacollab/projects/toolmodels/modelsources/git/gitlab/exceptions.py
- backend/capellacollab/projects/toolmodels/modelsources/git/gitlab/interface.py
- backend/capellacollab/projects/toolmodels/modelsources/git/gitlab/validation.py
- backend/capellacollab/projects/toolmodels/modelsources/git/routes.py
- backend/capellacollab/projects/toolmodels/modelsources/git/validation.py
- backend/capellacollab/settings/modelsources/git/core.py
- backend/capellacollab/settings/modelsources/git/routes.py
- backend/pyproject.toml
- backend/tests/projects/toolmodels/test_diagrams.py
- backend/tests/projects/toolmodels/test_model_badge.py
- frontend/src/app/projects/project-detail/model-overview/model-complexity-badge/model-complexity-badge.component.html
Loading the monitoring overview can take minutes when having many models.
We're waiting a lot for responses from the Gitlab API. This PR adds support for asynchronous calls in the Gitlab interface.
Tested it against a production database of our largest instance. Loading time of the monitoring view is reduced from 2.5 minutes to 8 seconds.
> feat: Make loading of monitoring overview async

- frontend/src/app/projects/project-detail/project-users/project-audit-log/project-audit-log.component.html
- frontend/src/app/projects/project-detail/project-users/project-audit-log/service/project-audit-log.service.ts
The audit log was not cleared when changing the project. It was displaying the results from the old project. 
Also, the affected user was not shown, only the person who produced the event.
> fix: Reset audit log on project change and display user

- backend/capellacollab/sessions/sessions.py
- helm/templates/prometheus/prometheus.configmap.yaml
So jupyter notebooks are automatically shut down after being idle for a while.
> feat: add inactive alert for jupyter notebooks

- backend/capellacollab/projects/toolmodels/models.py
- backend/capellacollab/sessions/routes.py
The `restrictions` table doesn't always exist.
This was not considered in the type annotation and wasn't checked properly when accesing the `allow_pure_variants` restriction.
Resolves https://github.com/DSD-DBS/capella-collab-manager/issues/866
> fix(pure-variants): Handle missing restrictions table

- backend/capellacollab/projects/toolmodels/modelsources/git/github/handler.py
This somehow seems flaky to me, as it worked before even though this code does not make sense, as we want to use the password if it exists and otherwise leave the headers as none
> fix: Use password for retrieving github artifacts

- backend/capellacollab/__main__.py
- backend/capellacollab/alembic/versions/d0cbf2813066_add_end_time_for_pipeline_run.py
- backend/capellacollab/config/config_schema.yaml
- backend/capellacollab/core/logging/exceptions.py
- backend/capellacollab/core/logging/loki.py
- backend/capellacollab/projects/toolmodels/backups/exceptions.py
- backend/capellacollab/projects/toolmodels/backups/models.py
- backend/capellacollab/projects/toolmodels/backups/routes.py
- backend/capellacollab/projects/toolmodels/backups/runs/interface.py
- backend/capellacollab/projects/toolmodels/backups/runs/models.py
- backend/capellacollab/projects/toolmodels/backups/runs/routes.py
- backend/config/config_template.yaml
- backend/tests/projects/toolmodels/pipelines/pipeline-runs/test_pipeline_runs.py
- backend/tests/projects/toolmodels/pipelines/test_pipelines.py
- frontend/src/app/projects/models/backup-settings/pipeline-runs/wrapper/pipeline-run-wrapper/pipeline-run-wrapper.component.ts
- frontend/src/app/projects/models/backup-settings/view-logs-dialog/view-logs-dialog.component.css
- frontend/src/app/projects/models/backup-settings/view-logs-dialog/view-logs-dialog.component.html
- frontend/src/app/projects/models/backup-settings/view-logs-dialog/view-logs-dialog.component.ts
- helm/config/backend.yaml
- helm/values.yaml
Please check the commit messages for detailed information.
The main improvements are: 
- Logs and events for finished jobs are only fetched once, not every two seconds (they won't change anymore)
- The query time range for Grafana Loki calls was reduced, leading to less calls inside of Grafana Loki
- Add handling of TooManyRequests error in Grafana Loki 
- Jobs are properly terminated. Logs and events are fetched before termination. 
Resolves #852
Resolves #864
> feat: Improve the "logs" experience and reduce number of backend calls

- guacamole/Dockerfile
- guacamole/ext/guac-manifest.json
- guacamole/ext/guac-manifest.json.license
- guacamole/ext/translations/en.json
- guacamole/ext/translations/en.json.license
- guacamole/guacamole.properties
During container startup, the new Capella Collaboration Manager extension for Guacamole is loaded: 
```
18:35:11.023 [localhost-startStop-1] INFO  o.a.g.extension.ExtensionModule - Extension "Capella Collaboration Manager extension" (capellacollab) loaded.
```
At the beginning, it's just changing the english translation, mostly to replace Guacamole with "Capella Collaboration Manager session".
For example, this is the message during connection: 
Error handling can now give the hint to check the current session status in the Collaboration Manager: 
Also, the Guacamole logout screen provides more information how to continue:
> feat: Add custom branding of Guacamole

- frontend/src/app/general/nav-bar-menu/nav-bar-menu.component.html
- frontend/src/app/general/nav-bar-menu/nav-bar-menu.component.ts
In the mobile view, the log out button was only
displayed for administrators, not for users.
This commit adds the Log out button for all users
in the mobile navigation.
> fix: Display log out button in mobile view

- frontend/src/app/projects/models/create-model/create-model.component.ts
- frontend/src/app/projects/models/model-source/choose-source.component.html
Sometimes, users don't have a source ready during model creation. In these cases, they now can skip the source creation.
> feat: Add option to skip source linking

- backend/capellacollab/__main__.py
- backend/capellacollab/core/exceptions.py
- backend/capellacollab/tools/routes.py
Some elements can only be deleted or modified if
no objects depend on the object to delete.
If this rule is not met, we throw the new
ExistingDependenciesError.
> refactor: Add custom ExistingDependenciesError

- frontend/src/app/projects/project-detail/model-overview/model-overview.component.html
The model badge is Capella exclusive and should
not be displayed for other tools.
> fix: Only display model badge for Capella models

- backend/capellacollab/core/authentication/provider/azure/routes.py
- backend/capellacollab/core/authentication/provider/oauth/routes.py
- backend/capellacollab/projects/routes.py
- backend/capellacollab/projects/toolmodels/routes.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/settings/modelsources/t4c/repositories/routes.py
- backend/capellacollab/users/events/routes.py
- backend/capellacollab/users/routes.py
A trailing slash leads to a temporary redirect when calling the route without trailing '/'.
This in unwanted behaviour and slows down the frontend.
> fix: Remove trailing '/' from fastapi routes

- backend/capellacollab/core/pydantic.py
- backend/capellacollab/projects/toolmodels/backups/models.py
- backend/capellacollab/projects/toolmodels/backups/runs/interface.py
- backend/capellacollab/projects/toolmodels/backups/runs/models.py
- backend/capellacollab/projects/toolmodels/backups/runs/routes.py
- backend/capellacollab/projects/toolmodels/diagrams/models.py
- backend/capellacollab/sessions/crud.py
- backend/capellacollab/sessions/models.py
- backend/capellacollab/users/crud.py
- backend/capellacollab/users/events/crud.py
- backend/capellacollab/users/events/models.py
- backend/pyproject.toml
- backend/tests/projects/toolmodels/pipelines/pipeline-runs/conftest.py
The backend has used different timezones to store datetimes. Sometimes, the local ast timezone was used, sometimes UTC.
In this commit, all datetime objects are now stored in UTC. The backend adds the timezone information to all backend responses.
With the new timezone in the response, Angular automatically maps the datetime to the client timezone.
Thanks to @Wuestengecko for finding this bug.
> fix: Add timezone awareness in frontend and backend

- .gitattributes
- backend/capellacollab/alembic/versions/97c7acd616fc_add_configuration_to_toolmodels.py
- backend/capellacollab/core/database/migration.py
- backend/capellacollab/projects/toolmodels/crud.py
- backend/capellacollab/projects/toolmodels/models.py
- backend/capellacollab/projects/toolmodels/routes.py
- backend/capellacollab/projects/toolmodels/workspace.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/sessions/workspace.py
- backend/tests/projects/toolmodels/test_jupyter_fileshare.py
- backend/tests/sessions/test_sessions_routes.py
- docs/development/mkdocs.yml
- docs/user/docs/sessions/jupyter/collaboration.md
- docs/user/docs/sessions/jupyter/jupyter-collaboration.mp4
- docs/user/docs/sessions/jupyter/jupyter-collaboration.mp4.license
- docs/user/mkdocs.yml
During creation of a Jupyter model in a project, a file-share is created. This feature enables project-wide file-shares. Together with internal projects, it can even serve as global file-share. Per default, the size of the volume is 2GB.
To delete a file-share, just delete the model from the project.
The feature is not complete yet. File-shares are created, but not mounted. The state of the Kubernetes operator is currently not good enough for mounting. We have another PR open to improve the situation. Once the `session hooks` PR is merged, we can build the mounting-feature for Jupyter file-shares: https://github.com/DSD-DBS/capella-collab-manager/pull/912.
Nevertheless, I would merge this PR and implement mounting in a later PR.
Depends on #900, #901, #902, #903, #904 and #905.
> feat: Add project-wide Jupyter notebook "share" for collaboration

- backend/capellacollab/alembic/versions/4c58f4db4f54_replace_tool_specific_session_.py
- backend/capellacollab/sessions/hooks/__init__.py
- backend/capellacollab/sessions/hooks/interface.py
- backend/capellacollab/sessions/hooks/jupyter.py
- backend/capellacollab/sessions/hooks/pure_variants.py
- backend/capellacollab/sessions/hooks/t4c.py
- backend/capellacollab/sessions/models.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/sessions/sessions.py
- backend/capellacollab/sessions/util.py
- backend/tests/conftest.py
- backend/tests/sessions/test_session_hooks.py
- backend/tests/sessions/test_sessions_routes.py
The sessions routes and the kubernetes operator grew a lot in the past. These two files can be hard to understand and code quality was rather bad.
A lot of tool-specific logic happened in the two files, e.g., the creation of a T4C session token.
This logic doesn't belong to the operator or the sessions module, the context is tool-specific, but it has a strong connection to the sessions lifecycle.
The solution is session hooks. For the beginning, we support the following hooks:
- configuration_hook (Configuration for the session)
- post_session_creation_hook (Hook executed after session creation)
- post_session_termination_hook (Hook executed after session termination)
The T4C, pure::variants and Jupyter logic was moved to session-hooks.
This is just a start and should make refactoring of …
> feat: Introduce session hooks

- backend/capellacollab/sessions/hooks/interface.py
- backend/capellacollab/sessions/hooks/t4c.py
The T4C integration hook is only called if the T4C integration is enabled. Therefore, we can remove the check within the hook.
> refactor: Remove unnecessary T4C integration check

- frontend/src/app/projects/models/model-detail/model-detail.component.css
- frontend/src/app/projects/models/model-detail/model-detail.component.html
- frontend/src/app/projects/models/model-detail/model-detail.component.ts
- frontend/tailwind.config.js
- TeamForCapella repositories are only displayed if the user is administrator and the tool has a TeamForCapella integration.
- The margin was moved from the inner mat-card to the outer a-element. The cursor doesn't trigger in the margin area anymore.
- The never implemented "Create new repository" for Git & T4C were removed.
> refactor: Cleanup model sources

- backend/capellacollab/projects/toolmodels/backups/exceptions.py
- backend/capellacollab/projects/toolmodels/backups/runs/injectables.py
- backend/capellacollab/projects/toolmodels/diagrams/routes.py
- backend/capellacollab/projects/toolmodels/modelbadge/routes.py
- backend/capellacollab/projects/toolmodels/modelsources/git/exceptions.py
- backend/capellacollab/projects/toolmodels/modelsources/git/gitlab/exceptions.py
- backend/capellacollab/projects/toolmodels/modelsources/git/handler/exceptions.py
- backend/capellacollab/projects/toolmodels/modelsources/git/injectables.py
- backend/capellacollab/projects/toolmodels/modelsources/git/routes.py
- backend/capellacollab/projects/toolmodels/restrictions/routes.py
- backend/capellacollab/projects/toolmodels/routes.py
- backend/capellacollab/sessions/files/routes.py
- backend/capellacollab/settings/modelsources/git/core.py
- backend/capellacollab/settings/modelsources/git/injectables.py
- backend/capellacollab/settings/modelsources/t4c/interface.py
- backend/capellacollab/settings/modelsources/t4c/repositories/routes.py
- backend/capellacollab/tools/routes.py
- backend/tests/projects/toolmodels/pipelines/test_pipelines.py
- backend/tests/projects/toolmodels/test_diagrams.py
- backend/tests/projects/toolmodels/test_model_badge.py
- backend/tests/settings/test_t4c_instances.py
Use 4xx status codes for issues that appear in our system. 
Not all "unhappy" flows are error flows. The application anticipates a lot of unhappy cases and should act accordingly.
Fixes #668.
> Clean up status codes

- backend/Dockerfile
Docker buildkit is not available when running
`az acr build`. To add support, we have to remove
the Docker BuildKit requirement.
Revert "perf: Use build cache for Docker build"
This reverts commit 3b23c78e0cc4a4504f53ced4b537e9ffc0d8f3ca.
> fix: Disable Docker Buildkit

- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/connect/guacamole-dialog/guacamole-dialog.component.css
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/connect/guacamole-dialog/guacamole-dialog.component.html
- frontend/src/app/settings/core/tools-settings/tool-details/tool-deletion-dialog/tool-deletion-dialog.component.html
- frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.component.html
- frontend/src/styles.css
- Hardcoded "Capella" references were removed. Instead, the tool name and tool version name are displayed.
- TeamForCapella is now shown conditionally depending on the activated TeamForCapella integration.
- Some CSS classes were replaced with Tailwind CSS.
- The TeamForCapella connection dialog was moved above the "Connect to session" step to match the typical workflow.
- mat-cards were replaced with simple div elements.
Screenshot of new design: 
Resolves #413
> refactor: Redesign session connection dialog

- backend/capellacollab/sessions/hooks/jupyter.py
- docs/user/docs/sessions/jupyter/collaboration.md
This is a follow-up of https://github.com/DSD-DBS/capella-collab-manager/pull/894.
In https://github.com/DSD-DBS/capella-collab-manager/pull/894, project-wide Jupyter file-shared were added, but not mounted to sessions. This missing bit is added in this PR.
The shares are mounted to `/shared/<project_slug>/<toolmodel_slug>`. To access the shares directly, a symlink from `/workspace/notebooks/shared` to `/shared` is required in the session container. This was added in https://github.com/DSD-DBS/capella-dockerimages/pull/187.
We do consider the access permission for users in projects:
- All users can see the file-shares from internal projects in a read-only mode.
- Administrators can access all file-shares in a read/write-mode
- Project members of private projects have access according to …
> feat: Add mounting for project-level Jupyter file-shares

- frontend/src/app/projects/create-project/create-project.component.html
- frontend/src/app/projects/create-project/create-project.component.spec.ts
- frontend/src/app/projects/create-project/create-project.component.ts
- frontend/src/app/projects/project-detail/project-users/service/project-user.service.ts
This adjusts the second step of the project creation. Up to now, there was always the "skip" button shown even if a user was added. As this is quite misleading this PR changes it such that the button states "continue" if at least one user was added.
Resolves: #632
> feat: Conditional display of skip or continue during user creation in the project creation

- frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.component.ts
Apparently the entrypoint field is not a required field in the strict sense since it has two error messages attached. Nevertheless, it confused me that it seems not to be required while at the same time throwing an error when being left empty.
> fix: Add asterisc to entry point when editiing the model sources

- backend/capellacollab/sessions/operators/k8s.py
For more information on this filter, please check out the comment in #941 
Resolves #941
> feat: Add promtail event filter

- helm/templates/backend/backend.serviceaccount.yaml
The deletion of Jupyter file-shares failed because of insufficient permissions in the sessions namespace.
This PR adds the "delete" verb to the "pvc" resource in the backend serviceaccount.
> fix: Add permission to delete Jupyter file share PVCs

- .pre-commit-config.yaml
- backend/capellacollab/config/loader.py
- backend/capellacollab/projects/toolmodels/modelsources/git/github/handler.py
- backend/tests/test_metrics.py
Update to the latest version of `black`, and switch to the official pre-commit mirror, which runs about 2x faster.
> Update pre-commit black

- frontend/src/app/app-routing.module.ts
- frontend/src/app/general/breadcrumbs/breadcrumbs.component.html
- frontend/src/app/general/header/header.component.css
- frontend/src/app/general/header/header.component.html
- frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.html
This PR mainly moves the breadcrumbs into a separate row below the main NavBar and makes them smaller. This has the advantage that even long breadcrumbs (e.g., long model names) will be displayed correctly. In addition, the breadcrumbs now also have a proper hover visualisation and some broken redirects were fixed. Lastly, just a few unnecessary breadcrumbs where removed (e.g., `projects / overview` -> `Projects`) and some breadcrumb names were adjusted.
Resolves #784
> feat: Redesign NavBar and Breadcrumbs

- frontend/src/app/settings/core/tools-settings/tool-details/tool-details.component.html
The fixed was could be reproduced by:
- Navigate to > Profile > Settings > Tools > (Choose any tool)
- Change name and/or docker images
- Press enter
- Refresh the page, the values are the old ones again, wasn't passed to the backend
> fix: Update of tool metadata didn't trigger on 'Enter'

- docs/user/docs/settings/tools/capella/t4c-git-compare.md
- docs/user/mkdocs.yml
The co-working methods TeamForCapella and Git are compared in a table.
> docs(user): Add quick comparision of Capella co-working methods

- helm/templates/guacamole/postgres.deployment.yaml
- helm/templates/guacamole/postgres.volume.yaml
When running the environment with target: local, the Guacamole database was not persistent. The database had to be reinitialized after each restart.
This can be annoying, also in local development environments. The specific Guacamole database handling for local environment is removed in this commit.
This will improve the local stability, see #800.
> feat: Make Guacamole database persistent in development mode

- Makefile
- helm/templates/routing/nginx.ingress.yaml
- helm/values.yaml
Before this commit, it was set to nginx on remote deployments. This is not flexible enough.
> feat: Make ingressClassName configurable

- .github/workflows/push.yml
- Makefile
- helm/templates/backend/backend.deployment.yaml
- helm/templates/backend/postgres.deployment.yaml
- helm/templates/backend/postgres.volume.yaml
- helm/templates/docs/docs.deployment.yaml
- helm/templates/frontend/frontend.deployment.yaml
- helm/templates/grafana/grafana.deployment.yaml
- helm/templates/grafana/nginx.deployment.yaml
- helm/templates/guacamole/guacamole.deployment.yaml
- helm/templates/guacamole/guacd.deployment.yaml
- helm/templates/guacamole/postgres.deployment.yaml
- helm/templates/prometheus/nginx.deployment.yaml
- helm/templates/prometheus/prometheus.deployment.yaml
- helm/templates/promtail/promtail.nodeport.yaml
- helm/templates/routing/nginx.deployment.yaml
- helm/values.yaml
Resolves #770
This commit adds support for local production deployments, see #800.
> refactor: Replace `target` with `development` in `values.yaml`

- Makefile
- helm/templates/promtail/promtail.networkpolicy.yaml
- helm/templates/routing/manager.networkpolicy.yaml
- helm/values.yaml
This PR introduces network policies for our sessions and the main namespace. The session network policies should forbid any incoming traffic except coming from the main namespace or the ingress (required for jupyter to work). Here, we could also include a more fine grained limitation of the ingress case by only allowing this from jupyter sessions. The main namespace should forbid any incoming traffic from the outside, except from the ingress (otherwise the collab manager would not be accessible). Furthermore, we have to allow traffic between pods in this namespace.
This PR requires to add the `ingressNamespace` property to the `values.yaml` (only required for non openshift cluster in the current state)
> feat: Add network policies

- README.md
- docs/user/docs/installation.md
- docs/user/mkdocs.yml
There is also a less detailed installation guide in the README. These instructions should be merged in a later PR.
> docs: Add installation guide to mkdocs

- backend/capellacollab/config/config_schema.yaml
- backend/capellacollab/sessions/hooks/jupyter.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/config/config_template.yaml
- backend/tests/sessions/test_sessions_routes.py
- helm/config/backend.yaml
- helm/templates/routing/nginx.ingress.yaml
- helm/values.yaml
In some environments, e.g. local unmanaged single-node clusters, it might make sense to serve the application on another host.
This feature was requested in #745.
Kubernetes ingress has support for wildcard hosts. I can be enabled by just setting the host to `null` in the ingress definition.
Also, the commit fixes an issue with reverse proxies, where the application didn't serve anymore because the internal host didn't match the one configured in the `values.yml`.
> feat: Add support for wildcard hosts

- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-dialog.component.html
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-dialog.component.ts
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.ts
The diagram overview and diagram viewer makes now full use of the available space on mobile phones.
As the previous way to close the diagram by just pressing next to it it not available anymore (there are no margins),
there is a new sticky close button on mobile phones.
The UI on devices with wider screens (>=1024px) doesn't change.
Thanks to @vik378 for proposing this improvement. 
A screenshot of the new UI (grey area is outside of the device screen):
> feat: Improve diagram cache margins on mobile phones

- backend/capellacollab/sessions/routes.py
- backend/tests/sessions/test_sessions_routes.py
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-model-options/create-readonly-model-options.component.ts
The selected branch was not passed to the backend, and the backend did not add it to the configuration of the session container.
Fixes #1072
> Fix readonly session branch selection

- .github/dependabot.yml
Instead of having a bunch of NPM updates provided by Dependabot, each one not building, group all Angular related updates, so we have one concise update for all Angular packages.
This way we do not have to do the frontend updates ourselves.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
> Group Angular updates in one PR

- backend/pyproject.toml
Add Python 3.12 to the supported Python versions.
Updated Trove classifiers. Just Python should be enough. Python 2 is no longer a thing, right? ;)
> Support Python 3.12

- backend/capellacollab/__main__.py
- backend/capellacollab/alembic/versions/f7bf9456cfc9_add_archive_flag.py
- backend/capellacollab/projects/toolmodels/modelsources/t4c/routes.py
- backend/capellacollab/settings/modelsources/t4c/exceptions.py
- backend/capellacollab/settings/modelsources/t4c/injectables.py
- backend/capellacollab/settings/modelsources/t4c/models.py
- backend/capellacollab/settings/modelsources/t4c/routes.py
- backend/tests/settings/conftest.py
- backend/tests/settings/test_t4c_instances.py
- backend/tests/settings/test_t4c_repositories.py
- docs/user/docs/settings/model-sources/t4c.md
- docs/user/mkdocs.yml
- frontend/src/app/projects/models/model-source/t4c/manage-t4c-model/manage-t4c-model.component.html
- frontend/src/app/services/settings/t4c-instance.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.html
This PR adds an archive flag to the t4c instances. When set the t4c instances should be grayed out in the drop down menu (i.e., no longer be selectable) and one should no longer be able to edit the instance. However, existing linked models should still work as expected.
Resolves #970
> feat: Add possibilities to archive t4c instances

- backend/capellacollab/config/config_schema.yaml
- backend/capellacollab/sessions/hooks/jupyter.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/config/config_template.yaml
- backend/tests/sessions/test_sessions_routes.py
- helm/config/backend.yaml
- helm/config/nginx.conf
- helm/templates/routing/nginx.ingress.yaml
- helm/values.yaml
When using a reverse proxy in front of the application, `$http_host` might point to an network internal address. The `proxy_redirect` response points to the internal address then, which leads to redirects to internal addresses (failing requests).
This is another improvement for the cluster setup on VMs (no managed clusters). Together with other merged PRs, this resolves #800.
> feat: Replace `$http_host` in nginx.conf, add support for proxies

- backend/capellacollab/core/database/__init__.py
The application stores the datatime objects in a timezone naive format. Therefore, we store them as UTC and also expect to get UTC as response.
We expect the database to run in UTC, it should not perform any additional datetime or timezone transformation. The transformation is done in the application.
However, some databases run in different timezones. In this case, we ensure that UTC is used for our transactions.
> fix: Ensure that PostgreSQL database uses 'UTC' timezone

- .gitmodules
Git submodules are often staged and committed accidentally. We are generally not supposed to commit dirty submodules, so we can let Git ignore them. Dirty submodules are no longer shown as modified in git status.
> build: Let Git ignore dirty `capella-dockerimages` submodule

- backend/capellacollab/projects/toolmodels/diagrams/routes.py
- backend/tests/projects/toolmodels/test_diagrams.py
- docs/user/docs/tokens.md
When using the diagram cache the route should not run into errors  when calling diagrams with a file ending or without.
> fix: Remove file ending in diagram route

- ci-templates/gitlab/image-builder.yml
- docs/.readthedocs.yaml
The docs were moved to the docs directory and are not located in the user subdirectory anymore.
> fix: Update some old references from `docs/user` to `docs`

- frontend/Makefile
Angular CLI could prompt the user for input about autocomplete or analytics in the middle of the make process, causing a failure to properly launch the app. Adding an environmental variable to suppress TTY avoids this.
> fix: Prevent Angular CLI prompts from interrupting app launch

- frontend/src/app/projects/models/model-description/model-description.component.ts
- frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.component.ts
- frontend/src/app/projects/models/model-source/t4c/manage-t4c-model/manage-t4c-model.component.ts
- frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.ts
This PR mainly changes the usage of `window.confirm` to the newly introduced custom dialog. In addition, unnecessary error cases in the corresponding functions are deleted.
> feat: Change `window.confirm` to custom dialog

- backend/capellacollab/projects/routes.py
- backend/capellacollab/projects/toolmodels/crud.py
- backend/capellacollab/projects/toolmodels/models.py
- backend/capellacollab/projects/toolmodels/routes.py
- backend/tests/projects/test_projects_routes.py
- backend/tests/projects/toolmodels/test_toolmodels.py
- frontend/src/app/app.module.ts
- frontend/src/app/projects/models/model-description/model-description.component.ts
- frontend/src/app/projects/models/service/model.service.ts
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.html
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.ts
- frontend/src/app/projects/project-detail/model-overview/move-model/move-model.component.css
- frontend/src/app/projects/project-detail/model-overview/move-model/move-model.component.html
- frontend/src/app/projects/project-detail/model-overview/move-model/move-model.component.ts
- frontend/src/app/projects/service/project.service.ts
closes #799 
currently the dialog looks like that:
> feat: Move model from one project to another

- .pre-commit-config.yaml
- backend/pyproject.toml
A few weeks ago, we required a pre-release version of [capellambse](https://github.com/DSD-DBS/py-capellambse) as dev dependency. Since they now already released two new versions, I just bumped the version to the most recent one to no longer depend on a pre-relase.
> chore: Bump capellambse to 0.5.36

- backend/capellacollab/core/database/migration.py
- backend/tests/projects/test_projects_routes.py
> feat: Add coffee machine as default model

- backend/capellacollab/sessions/operators/k8s.py
- backend/tests/sessions/k8s_operator/conftest.py
- backend/tests/sessions/k8s_operator/test_session_k8s_download.py
- backend/tests/sessions/k8s_operator/test_session_k8s_operator.py
- helm/templates/backend/backend.disruptionsbudget.yml
- helm/templates/backend/backend.serviceaccount.yaml
- helm/templates/backend/postgres.disruptionbudget.yml
- helm/templates/docs/docs.discruptionbudget.yml
- helm/templates/frontend/frontend.disruptionbudget.yml
- helm/templates/grafana/grafana.disruptionbudget.yml
- helm/templates/grafana/nginx.disruptionbudget.yml
- helm/templates/guacamole/guacamole.disruptionbudget.yml
- helm/templates/guacamole/guacd.disruptionbudget.yml
- helm/templates/guacamole/postgres.disruptionbudget.yml
- helm/templates/prometheus/nginx.disruptionbudget.yml
- helm/templates/prometheus/prometheus.disruptionbudget.yml
- helm/templates/routing/nginx.disruptionbudget.yml
Kubernetes allows a lot flexibility when it comes to cluster and node updates.
Cluster updates can happen at any time and can lead to massive interruptions (Guacamole not available) and session termination with potential data loss.
Pod discruption budgets define under which circumstances the cluster operator can terminate or restart Pods.
Our new policy is now:
- For each service of the management portal, at least one Pod has to be up&running at any time.
- Session termination by the control plane is not allowed. The cluster operator has to contact the system administrator or wait until the session is terminated.
Resolves #1089
> feat(k8s): Add Pod disruption budgets

- backend/capellacollab/config/diff.py
- backend/capellacollab/projects/routes.py
- backend/capellacollab/projects/toolmodels/modelsources/git/github/handler.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/settings/modelsources/git/askpass.py
- backend/pyproject.toml
There were again a few print statements, which messed up the logs.
We should use log messages instead of print statements. If a print statement is required, disable the pylint warning.
> ci: Prohibit use of `print` function

- docs/docs/user/projects/models/create.md
- frontend/src/app/projects/create-project/create-project.component.html
- frontend/src/app/projects/create-project/create-project.component.spec.ts
- frontend/src/app/projects/create-project/create-project.component.ts
- frontend/src/app/projects/models/create-model-base/create-model-base.component.html
- frontend/src/app/projects/models/create-model/create-model.component.html
- frontend/src/app/projects/models/create-model/create-model.component.ts
- frontend/src/app/projects/models/init-model/init-model.component.html
- frontend/src/app/projects/models/model-source/choose-source.component.html
- frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.component.html
- frontend/src/app/projects/models/model-source/t4c/create-t4c-model-new-repository/create-t4c-model-new-repository.component.html
- frontend/src/app/projects/models/model-source/t4c/manage-t4c-model/manage-t4c-model.component.html
- frontend/src/app/projects/project-detail/project-users/add-user-to-project/add-user-to-project.component.html
- frontend/src/app/projects/project-detail/project-users/project-user-settings.component.html
- frontend/src/app/projects/project-detail/project-users/project-user-settings.component.ts
- frontend/src/app/projects/service/project.service.ts
- frontend/src/app/settings/integrations/pure-variants/pure-variants.component.html
- frontend/src/styles.css
Photos show the old views on the left and updated views on the right. These changes also includes the removal of the unused "model initialization" step. Resolves issue #1110
> feat: Improve project creation UI

- frontend/src/app/projects/project-overview/project-overview.component.html
- frontend/src/app/settings/core/tools-settings/tools-settings.component.html
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.html
- frontend/src/app/settings/settings.component.css
- frontend/src/app/settings/settings.component.html
- frontend/src/styles.css
The clickable area in the mat-card overviews was slightly larger than the mat-card. Reason is that that the mat-card element has a margin of 10px and is wrapped by an a-element. The margin is now "moved" to the a-element.
> fix: Restrict clickable area on mat-card overviews

- frontend/angular.json
The project relies heavily on TailwindCSS and existing legacy components will moved their styles to TailwindCSS. For many new components, there is no need to a separate CSS file anymore, Tailwind covers most of the capabilities.
Also, we hardly use `.spec.ts` files and have only a small number of frontend tests. Therefore, they are also omitted during component or service creation.
> build(frontend): Skip creation of `.css` and `.spec.ts` files

- frontend/src/app/general/header/header.component.html
- frontend/src/app/general/nav-bar-menu/nav-bar-menu.component.html
Fixes #1164 
Moving routerLinks out of the containing divs and into the anchors for nav bar and side nav links makes them behave like normal links (middle click to open new tab, right click to open context menu, etc.)
> fix: Enable default link behaviors on nav bar and side nav links

- Makefile
- docs/docs/development/index.md
Developers can simply run `make dev` instead of `make -j4 dev`. Since the target does only work with parallel execution endabled, the parallel execution is now the default.
> build: No longer require `-j4` in `make dev`

- docs/docs/user/sessions/troubleshooting.md
The usual option to press `Control` while clicking doesn't work in RDP-sessions on macOS. The `Control` can't be evaluated and mapped properly. It's passed to the Linux container, which can't handle the `Control` key.
> docs(user): Add instructions for secondary click on macOS

- frontend/src/app/sessions/session/floating-window-manager/floating-window-manager.component.ts
- frontend/src/app/sessions/session/session-iframe/session-iframe.component.html
- frontend/src/app/sessions/session/session-viewer.service.ts
- frontend/src/app/sessions/session/tiling-window-manager/tiling-window-manager.component.html
- frontend/src/app/sessions/session/tiling-window-manager/tiling-window-manager.component.ts
This PR fixes a small bug that was introduced in #1150.
When the pointer events are not disabled on the iframe, some pointer events are "stolen" by the iframe. Therefore, they can not be used by our event handlers. This led to a "jumpy" behaviour while resizing.
> fix(session-viewer): Disable pointer event while resizing sessions

- backend/capellacollab/core/metadata.py
- backend/config/config_template.yaml
- frontend/.eslintrc.js
- frontend/angular.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/app.module.ts
- frontend/src/app/general/metadata/metadata.service.ts
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-code-block/model-diagram-code-block.component.html
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-code-block/model-diagram-code-block.component.ts
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-dialog.component.css
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-dialog.component.html
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-dialog.component.ts
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.ts
- frontend/tailwind.config.js
In order for users to better understand how a personal access token can be helpful the codesnippet from the docs is displayed in the frontend.
closes #598
> feat: Show code snipped in diagram cache dialog

- backend/capellacollab/alembic/versions/5ca7037ef183_project_type.py
- backend/capellacollab/projects/crud.py
- backend/capellacollab/projects/models.py
- backend/tests/projects/test_projects_routes.py
- frontend/src/app/projects/create-project/create-project.component.spec.ts
- frontend/src/app/projects/create-project/create-project.component.ts
- frontend/src/app/projects/models/backup-settings/view-logs-dialog/view-logs-dialog.component.css
- frontend/src/app/projects/models/backup-settings/view-logs-dialog/view-logs-dialog.component.html
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-dialog.component.html
- frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.html
- frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.ts
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.html
- frontend/src/app/projects/project-overview/project-overview.component.html
- frontend/src/app/projects/service/project.service.ts
- frontend/src/styles.css
Support different types of projects. Currently _general_ and _training_. 
By default you're creating a normal project. This is what most users tend to do and I think we should not bother with training projects upon project creation directly. You can, however, modify a project and set it to _training_.
Training mode is depicted by a "study" icon before the name. Maybe we want to change the color of the header too.
Synchronization and persistent session buttons are not shown for models in a training project.
No additional behavior has been implemented.
Related to #1004.
> feat: Training mode for projects

- .github/workflows/docs.yml
- docs/Makefile
The strict mode fails if `mkdocs` produces warnings. This helps to identify broken links or other errors.
> docs: Enable strict mode

- frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.html
> fix: Use wider input fields in project metadata dialog

- helm/templates/guacamole/postgres.deployment.yaml
The `-W` flag in psql is used to provide a password prompt to the user. However, this lead to a problem that the probes were no longer successful due to that. Chaning this to `-w' ensures that no prompt is given and additionally,
we don't need the password here.
> fix: Correctly call `psql` in probes

- .commitlintrc.yml
- .github/workflows/commits.yml
- .pre-commit-config.yaml
There was an issue that the exclamation mark wasn't parsed properly.
For example, the commit message "feat!: Test" was declined, but is valid.
> ci: Extend `commitlint` configuration with conventional commits

- frontend/src/app/app.module.ts
- frontend/src/app/helpers/editor/editor.component.html
- frontend/src/app/helpers/editor/editor.component.ts
- frontend/src/app/settings/core/configuration-settings/configuration-settings.component.html
- frontend/src/app/settings/core/configuration-settings/configuration-settings.component.ts
The editor is moved to it's own component. This makes it usable for other components.
The interface to talk to the EditorComponent is as follows:
In the HTML template:
```html
<app-editor #editor (submitted)="yourOwnSubmitFunction($event)>
<button (click)="editor.submitValue()" />
<button (click)="editor.resetValue()" />
```
In the TS file:
```ts
// Fetch the editor component as variable
@ViewChild(EditorComponent) editor: EditorComponent | undefined;
// Set the editor value (pass JavaScript objects)
this.editor.value = {}
// Implement a submitValue handler:
yourOwnSubmitFunction(value: any){
console.log(value);
}
```
Depends on https://github.com/DSD-DBS/capella-collab-manager/pull/1168
> refactor: Make YAML editor reusable

- frontend/src/app/helpers/confirmation-dialog/confirmation-dialog.component.html
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-dialog.component.html
- frontend/src/app/projects/models/diagrams/model-diagram-preview-dialog/model-diagram-preview-dialog.component.html
- frontend/src/app/projects/models/model-description/model-description.component.html
- frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.html
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.html
- frontend/src/app/projects/project-detail/model-overview/move-model/move-model.component.html
- frontend/src/app/projects/project-detail/model-overview/reorder-models-dialog/reorder-models-dialog.component.html
- frontend/src/app/projects/project-detail/project-users/project-user-settings.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.html
- frontend/src/app/settings/core/pipelines-overview/pipelines-overview.component.css
- frontend/src/app/settings/core/user-settings/user-settings.component.html
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html
- frontend/src/styles.css
Lingering issues copied from #1195:
> fix: Minimize styling changes affected by Angular upgrade

- backend/capellacollab/__main__.py
- backend/capellacollab/projects/injectables.py
- backend/capellacollab/projects/toolmodels/backups/injectables.py
- backend/capellacollab/projects/toolmodels/backups/runs/injectables.py
- backend/capellacollab/projects/toolmodels/injectables.py
- backend/capellacollab/projects/toolmodels/modelsources/git/routes.py
- backend/capellacollab/projects/toolmodels/routes.py
Make them clearer and easier to understand.
> refactor: Optimize some error messages

- backend/capellacollab/projects/toolmodels/backups/runs/interface.py
The debug messages has spammed the log, which is esp. annoying while developing as it constantly prints new messages into the pdb terminal.
> chore: Remove debug message for job scheduling

- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-code-block/model-diagram-code-block.component.html
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-dialog.component.html
- frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.component.html
- frontend/src/app/projects/project-detail/project-users/project-user-settings.component.html
- frontend/src/app/sessions/session/session.component.html
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.html
- frontend/src/app/settings/core/user-settings/user-settings.component.html
Copied from #1317 
Requested changes:
Other stuff:
- Put icons on the right side in a few places where it was still on the left
- Open internal session viewer, open session viewer
http://localhost:4200/settings/modelsources/git
@MoritzWeber0 The above issue wasn't a problem for me locally at any width so I didn't make any changes (see below), but let me know if you continue to see it.
> fix: Update styling to minimize changes from Angular upgrade

- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-code-block/model-diagram-code-block.component.html
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/connection-dialog/connection-dialog.component.html
- frontend/src/styles.css
In some dialogs components, a scrollbar has appeared due to a touch target on the button, which was larger than the actual button itself.
To prevent similar cases, I'd disable it globally.
> fix: Remove button touch target to prevent scrollbars

- frontend/.eslintrc.js
- frontend/src/app/app-routing.module.ts
- frontend/src/app/general/auth/auth-guard/auth-guard.service.ts
We had to disable the deprecation rule due to many deprecated modules after an Angular update. After replacing all deprecated modules step by step, we can reenable the rule again.
> ci: Reenable deprecation ESLint rule

- backend/tests/conftest.py
- backend/tests/projects/toolmodels/pipelines/test_pipelines.py
- backend/tests/users/test_tokens.py
This update significantly enhances test execution efficiency by invoking the `migrate_db` function just once for all tests. More precisely with the changes running all tests took around **32 seconds** while running the tests on the main branch takes around **3 minutes and 15 seconds**. This optimization is accomplished by maintaining database changes in memory, rather than persisting them with `db.commit()`. Consequently, it is essential to expire all objects in scenarios where `db.commit()` would have been typically used. This approach introduces minimal overhead, given the limited number and frequency of object interactions during testing.
Additionally, some test cases have been modified to accommodate this change. They now rely on dynamic ids returned from the backend instead of static …
> feat: Improve test runtime by only calling `migrate_db` once

- .github/workflows/commits.yml
Global installations don't work since the release of version v19.0.0: https://github.com/conventional-changelog/commitlint/issues/3936
> ci: Install commitlint locally, not globally

- .github/workflows/push.yml
- ci-templates/gitlab/image-builder.yml
- docs/docs/admin/ci-templates/gitlab/k8s-deploy.md
- frontend/angular.json
The `environment.ts` doesn't contain any user-defined variables anymore. They were all moved to the backend configuration.
Therefore, we can remove the option to customize the `environment.prod.ts`
> build: Remove `environment.prod.ts`

- frontend/src/app/general/nav-bar/nav-bar.service.ts
- frontend/src/app/projects/project-detail/model-overview/model-complexity-badge/model-complexity-badge.component.ts
- frontend/src/environments/environment.dev.ts
- frontend/src/environments/environment.ts
Grafana, Prometheus and Documentation are not available on relative pathes in the development mode. Instead, they have to point to corresponding absolute URLs.
Documentation will point to the mkdocs serve.
Grafana & Prometheus to the local cluster deployment.
Same as https://github.com/DSD-DBS/capella-collab-manager/pull/1356, but this time with main as target branch.
> feat: Make external links available in development mode

- backend/capellacollab/__main__.py
The uvicorn error logger was disabled in #440 when our own logger was introduced. Unfortunately, our own logger doesn't work in all stages of the application.
For example, add a startup script which raises an exception to the on_startup list. The application startup will fail, but there is no error message.
This makes debugging hard and errors are overseen. The commit reenables the error log.
> fix: Reenable uvicorn error logger

- backend/capellacollab/alembic/versions/6c4ff61acc8e_add_resources_to_tools.py
- backend/capellacollab/core/database/migration.py
- backend/capellacollab/projects/toolmodels/backups/core.py
- backend/capellacollab/projects/toolmodels/backups/routes.py
- backend/capellacollab/projects/toolmodels/backups/runs/interface.py
- backend/capellacollab/projects/toolmodels/restrictions/routes.py
- backend/capellacollab/projects/toolmodels/routes.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/tools/crud.py
- backend/capellacollab/tools/models.py
- backend/tests/projects/toolmodels/pipelines/test_pipelines.py
- backend/tests/sessions/k8s_operator/test_session_k8s_operator.py
- backend/tests/sessions/test_sessions_routes.py
Instead of the hard-coded resource configuration, it can now be set per tool.
In addition, this commit adds job labels to cronjobs.
Resolves #1136.
> feat: Make resources configurable per tool

- backend/pyproject.toml
The newest version of `fastapi-pagination` breaks the pydantic resolution in our codebase. I've opened an issue in their repository.
https://github.com/uriyyo/fastapi-pagination/issues/1068
For now, I'll downgrade the dependency version.
> fix: Downgrade `fastapi-pagination` dependency

- helm/templates/prometheus/prometheus.deployment.yaml
- helm/templates/prometheus/prometheus.volume.yaml
Prometheus will now store the idletime of sessions and newly introduced TeamForCapella license usage. This allows us to look back to time frames before the last restart.
> feat: Make Prometheus persistent

- helm/templates/backend/backend.deployment.yaml
The backend constantly got OOMKilled in the local development cluster deployment.
> build(dev): Increase backend memory limits

- helm/config/grafana/active-sessions.json
- helm/config/grafana/active-sessions.json.license
- helm/config/grafana/team4capella.json
- helm/config/grafana/team4capella.json.license
- helm/templates/grafana/grafana-dashboards.configmap.yaml
- helm/templates/grafana/grafana.configmap.yaml
- helm/templates/grafana/grafana.deployment.yaml
Currently, we have two pre-defined dashboards, which are now provisioned automatically.
Please note that provisioned dashboards can not be edited or deleted in the UI.
If new dashboards should be added, just add a json file to `helm/config/grafana`, it will be picked up automatically.
Resolves #670.
Two dashboards are available for the beginning in the folder "Provisioned dashboards": 
The first gives an overview over active sessions and their activity: 
The second gives an overview over used TeamForCapella licenses, requires https://github.com/DSD-DBS/capella-collab-manager/pull/1387:
> feat: Automatically provision dashboards in Grafana

- frontend/src/app/projects/models/service/model.service.ts
- frontend/src/app/projects/project-detail/project-users/service/project-user.service.ts
- frontend/src/app/services/load-files/load-files.service.ts
- frontend/src/app/services/user/user.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/service/t4c-repos/t4c-repo.service.ts
A trailing slash leads to an unnecessary redirect, triggered by the backend. In addition, it's harder readable when a `/` is part of a base URL, which is then used in template literals, e.g. `${baseURL}/${resource}` is better to read than `${baseURL}${resource}`.
The redirect behaviour lead to occasional request failues and some parts of the frontend stopped working when running behind a reverse proxy with TLS edge termination.
> fix(frontend): Remove trailing `/` from backend API requests

- backend/capellacollab/projects/toolmodels/backups/runs/interface.py
This fixes a bug that pipelines weren't scheduled when triggered manually.
> fix: Pass resources to manually schedules jobs

- frontend/src/app/sessions/delete-session-dialog/delete-session-dialog.component.css
- frontend/src/app/sessions/delete-session-dialog/delete-session-dialog.component.html
- frontend/src/app/sessions/delete-session-dialog/delete-session-dialog.component.ts
This PR adds the tool information to the session termination dialog in the same format as it is displayed in the session card. This makes it easier for a user to identify which session is being closed when they click on "Terminate", as the ID is not known to the user. In addition, the empty css file has been removed and the new Angular control is now used in the component.
> feat: Add tool info to session deletion dialog

- backend/capellacollab/__main__.py
- backend/capellacollab/core/logging/__init__.py
- helm/templates/promtail/promtail.configmap.yaml
Log messages have different colors depending on the log level. This makes it easier to identify warnings and errors.
In addition, the date format is now the ISO format and includes the timezone information.
> feat: Add colored log messages

- backend/tests/test_event_creation.py
Eliminates the following deprecation warning in test_create_user_removed_from_project_event.
https://www.python-httpx.org/compatibility/#request-content - "content" is preferred over "data" in this scenario
tests/test_event_creation.py::test_create_user_removed_from_project_event
/Users/nicholasromeo/code/capella-collab-manager/.venv/lib/python3.11/site-packages/httpx/_content.py:204: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.
warnings.warn(message, DeprecationWarning)
> fix: Update user test to eliminate deprecation warning in request

- backend/capellacollab/core/authentication/__init__.py
- docs/docs/development/backend/extensions.md
Fix for the following deprecation warning:
capellacollab/core/authentication/__init__.py:14
capellacollab/core/authentication/__init__.py:14
/Users/nicholasromeo/code/capella-collab-manager/backend/capellacollab/core/authentication/__init__.py:14: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
for i in metadata.entry_points()[
> fix: Remove deprecated interface in authentication

- helm/templates/backend/postgres.deployment.yaml
- helm/templates/docs/docs.deployment.yaml
- helm/templates/frontend/frontend.deployment.yaml
- helm/templates/grafana/nginx.deployment.yaml
- helm/templates/guacamole/guacamole.deployment.yaml
- helm/templates/guacamole/guacd.deployment.yaml
- helm/templates/guacamole/postgres.deployment.yaml
- helm/templates/mock/oauth.deployment.yaml
- helm/templates/prometheus/nginx.deployment.yaml
- helm/templates/prometheus/prometheus.deployment.yaml
Service accounts aren't needed for most of the services since they don't talk to the Kubernetes API.
For increased security, this disables the automatic mounting of secrets.
> feat: Disable automatic service account mounting

- docs/docs/development/backend/extensions.md
We don't have support for extensions anymore and they are not loaded.
> docs: Remove extensions entrypoints from documentation

- backend/capellacollab/__main__.py
- backend/capellacollab/core/exceptions.py
- backend/capellacollab/core/logging/exceptions.py
- backend/capellacollab/projects/toolmodels/backups/exceptions.py
- backend/capellacollab/projects/toolmodels/exceptions.py
- backend/capellacollab/projects/toolmodels/modelsources/git/exceptions.py
- backend/capellacollab/projects/toolmodels/modelsources/git/gitlab/exceptions.py
- backend/capellacollab/projects/toolmodels/modelsources/git/handler/exceptions.py
- backend/capellacollab/sessions/exceptions.py
- backend/capellacollab/sessions/util.py
- backend/capellacollab/settings/modelsources/t4c/exceptions.py
- backend/capellacollab/tools/exceptions.py
- backend/capellacollab/users/exceptions.py
- backend/capellacollab/users/routes.py
- backend/tests/settings/teamforcapella/test_t4c_instances.py
- docs/docs/development/backend/exception.md
As a step towards resolving issue #1369, this PR:
- Adds a class BaseError to the core exceptions module for other exceptions to inherit from
- Required: _status_code_, _title_, _reason_. Optional: _err_code_. (_technical_ was not included as it only existed on one error at this time)
- Updates all existing exceptions defined in external exceptions files to use BaseError, and updates them to meet its requirements if they did not already
- Generates and registers exception handlers for all of BaseErrors children in the main application
- (and as a result removes all excess handler definitions, handler registrations, and imports throughout the exception files and main app file)
- Updates the documentation to reflect the new format
> feat: Add base error model, remove dupe error handlers and registration

- helm/templates/grafana/grafana.deployment.yaml
- helm/templates/prometheus/prometheus.deployment.yaml
This PR reverses a change that was introduced in https://github.com/DSD-DBS/capella-collab-manager/pull/1414, where the automatic mounting of service accounts for Prometheus was disabled. This is necessary because Prometheus needs access to the kubernetees API for its service discovery. 
Additionally, this PR adds the `Recreate` strategy to two deployments that use at least one volume with the `ReadWriteOnce` storage access mode. This is required to properly apply changes and deploy these components, because otherwise the creation will be blocked by the existing pod.
> fix: Automount service token to prometheus

- backend/capellacollab/core/database/migration.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/settings/modelsources/t4c/models.py
- backend/capellacollab/settings/modelsources/t4c/repositories/routes.py
- backend/pyproject.toml
- backend/tests/settings/teamforcapella/conftest.py
This PR enables pylints' invalid-name rule, i.e., C0130 and fixes resulting issues. One issue was properly fixed by changing constant enum fields to uppercase and two other issues were simply ignored. The first ignored issue, i.e., the naming problem of `T4CRepositoriesResponseModel` is not compliant due to the two directly preceding capital letters `CR`, which is intended here. The second problem is a false positive, since `pod_security_context` is considered a *constant*, but there are two places where we assign it a value, i.e., it is not actually constant.
Resolves #1379
> feat: Enable pylints' invalid name rule C0103

- backend/capellacollab/core/database/migration.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/settings/modelsources/t4c/models.py
- backend/capellacollab/settings/modelsources/t4c/repositories/routes.py
- backend/pyproject.toml
- backend/tests/settings/teamforcapella/conftest.py
This reverts commit addaf07d5542f9bfb5c92a4553b680c1ac71c0dd.
Reason is a failing backend startup with the following stacktrace:
```python
ERROR:    Traceback (most recent call last):
File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1637, in _object_value_for_elem
return self._object_lookup[elem]
~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'tcp'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/Users/moritzweber/Projects/github/capella-collab-manager/backend/.venv/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
async with self.lifespan_context(app) as maybe_state:
File …
```
> Revert "feat: Enable pylints' invalid name rule C0103"

- docs/mkdocs.yml
Loading fonts from Google Fonts is not GDPR compliant. Instead, fall-back to the system font.
> docs: Disable font loading from Google fonts

- helm/templates/sessions/sessions.configmap.yaml
nginx did resolve some encodings in the sessions proxy, for example %20 was rewritten to a whitespace. This led to "Bad request" errors in sessions.
The behaviour itself is interesting, the workaround too. I found the solution on StackOverflow:
https://stackoverflow.com/a/31440150
> fix(sessions): Don't resolve encodings in sessions proxy

- .github/workflows/storybook.yml
The first created comment was not considered as base for the second comment. Therefore, a second comment was created.
> ci: Fix duplicated creation of Storybook comment

- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.ts
This moves the logic of enabling version selection from an attribute to the actual logic. First of all, this removes the warning that angular always showed in the console about how we handled disabling the selection here. Second, once a tool is selected, there is no way to go back to the state where the version dropdown should be disabled, so just handling the enable case in the logic is quite simple. Finally, the current approach was not working properly because even without a tool selected, the version selector seemed to be enabled, i.e. we were even able to interact with it.
> fix: Correctly handle disabling version selection

- .github/workflows/storybook.yml
For a clear history, we have to build Chromatic on the main branch to have a comparision baseline.
> ci: Run Chromatic on 'main' branch

- backend/capellacollab/sessions/exceptions.py
- backend/capellacollab/sessions/hooks/provisioning.py
- backend/capellacollab/tools/models.py
- backend/tests/sessions/hooks/test_provisioning_hook.py
- backend/tests/tools/fixtures.py
- frontend/.prettierignore
- frontend/src/app/app.module.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-model-options/create-readonly-model-options.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-model-options/create-readonly-model-options.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-session-dialog.component.docs.mdx
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-session-dialog.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-session-dialog.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-session-dialog.stories.ts
- frontend/src/app/settings/core/tools-settings/tool.service.ts
This allows the administrator to configure the maximum number of models of a tool that can be provisioned. This is initially required for the Model Explorer, which currently supports only a single model. To do this, the backend will throw an exception if a user requests more than the specified number of sessions. In addition, we will also tell the user the maximum number of selectable sessions in the frontend in case they select more than possible.
Based on #1469 
Resolves #1446
> feat: Limit the number of models requested

- backend/capellacollab/tools/routes.py
- backend/tests/tools/test_tools_natures_routes.py
- backend/tests/tools/test_tools_version_routes.py
- frontend/.storybook/preview.ts
- frontend/src/app/app.module.ts
- frontend/src/app/projects/models/init-model/init-model.component.ts
- frontend/src/app/projects/models/model-description/model-description.component.ts
- frontend/src/app/sessions/service/session.service.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/create-session-history.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/create-session-history.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/create-session-history.docs.mdx
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/create-session-history.stories.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/session-history.service.ts
- frontend/src/app/settings/core/tools-settings/tool-details/tool-version/tool-version.component.ts
- frontend/src/app/settings/core/tools-settings/tool.service.ts
- frontend/src/app/settings/core/tools-settings/tools-settings.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
The last three requested sessions are cached locally and can be used to quick-request those sessions again.
The session history is lazy-loaded, so it doesn't slow down loading of the page.
> feat: Remember last requested sessions locally

- backend/capellacollab/sessions/exceptions.py
- backend/capellacollab/sessions/hooks/persistent_workspace.py
- backend/capellacollab/tools/models.py
- backend/tests/sessions/hooks/test_persistent_workspace.py
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-session-dialog.stories.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/create-session-history.stories.ts
- frontend/src/app/settings/core/tools-settings/tool.service.ts
Some tools can't handle persistent workspaces. Instead, they only support read-only sessions.
> feat: Disable persistent workspace sessions for specific tools

- backend/capellacollab/sessions/operators/k8s.py
It was broken since it still referenced the id as container ID. It was changed to "session" in an earlier PR.
> fix: List files in file browser works again

- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.css
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.docs.mdx
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.html
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.stories.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-session-dialog.stories.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/create-session-history.stories.ts
This first introduces the new angular control flow in this component. By doing so, we can easily add `track session.id` to the session loop. By tracking sessions by their id, only newly created or modified sessions are reloaded in the DOM. This not only improves performance by reducing the number of reloads, but also allows us to properly select parts of the session information, since previously each reload removed the selection. Finally, we also cleaned up the unused `sessions` variable and converted most of the styling to tailwind.
In addition, this PR also introduces stories for the Active Sessions component. These stories cover loading sessions, no active sessions, success, warning, error, and unknown states, as well as persistent and read-only sessions. It also includes a small fix …
> fix(front): Reload active session in DOM only on change or modification

- .github/workflows/commits.yml
- .github/workflows/push.yml
- .github/workflows/storybook.yml
Some actions always fail for dependabot PRs.
We should disable those.
> ci: Disable some Actions for dependabot PRs

- frontend/.eslintrc.js
https://github.com/sweepline/eslint-plugin-unused-imports/issues/77 is fixed. That's why we can reenable the rule.
> build: Reenable 'no-unused-imports' eslint rule

- backend/startup.sh
When FastAPI sent a temporary redirect, it didn't respect the `X-Forwarded-Proto` header of the proxy.
Therefore, it did default to `http` and sent an http URL as response.
In this commit we tell uvicorn to trust all IPs. Since the backend is firewalled and only reachable behind the Kubernetes Ingress / proxy, this is safe.
> fix: Trust proxy headers to avoid https -> http redirects

- docs/docs/user/projects/access/index.md
- docs/docs/user/projects/add-user/index.md
Was unclear for a user, let's add it to the documentation.
> docs: Users have to log in before project assignment

- backend/capellacollab/core/database/migration.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/routes.py
- backend/tests/sessions/k8s_operator/test_session_k8s_operator.py
- backend/tests/sessions/test_session_environment.py
- frontend/src/app/settings/core/tools-settings/tool-details/tool-details.component.ts
- helm/config/grafana/active-sessions.json
- helm/templates/prometheus/prometheus.configmap.yaml
- helm/templates/prometheus/prometheus.deployment.yaml
Filter active sessions by tool, tool version, connection method and session type.
The values are available as annotations on the Kubernetes service, deployment and pod. Prometheus relabels the annotations to labels.
In Grafana, a dropdown menu allows filtering:
In addition, the dashboard also shows sessions with failed activity monitoring.
Also, a small bug that tools couldn't be updated without the ID attribute is fixed.
> feat(monitoring): Filter active sessions by session variables

- backend/capellacollab/core/authentication/injectables.py
- backend/pyproject.toml
- backend/tests/core/test_auth_injectables.py
This PR enables the McCabe [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) check for pylint. This forces us not to make extensive use of nesting within functions, but to outsource parts to separate functions. For now we use the default threshold value of *10*.
Resolves #1380
> feat: Introduce McCabe complexity check

- backend/capellacollab/sessions/idletimeout.py
- backend/capellacollab/sessions/injection.py
- backend/tests/sessions/test_session_idletimeout.py
The automatic termination of idle sessions stopped working with #1573. Reason is that the app label was removed from Prometheus.
This commit migrates the old app references to the new session_id label.
> fix: Termination of sessions

- backend/capellacollab/sessions/operators/k8s.py
Failing session containers can result in restart loop until the garbage cleaner terminates the session after 90 minutes.
Most of the failing containers do fail after restarts again and produce unnecessary costs.
In the rare cases of one-time failures, the session can be created again in the frontend / via the API.
> feat: Never restart session containers

- backend/Makefile
To ensure that `(cd backend && make install)` works when there is no `backend/.venv`.
> fix: Create backend venv if not existing

- frontend/.storybook/main.ts
- frontend/.storybook/tsconfig.json
- frontend/Makefile
Storybook did spam the terminal with messages, which is especially annoying when running `make dev`.
This PR reduces the log level by adding the --quite flag.
In addition, there were some valid WARN messages about wrong usage of the files attribute in the `tsconfig.json`. Those warnings are resolved.
> fix: Reduce Storybook log level and fix warnings

- backend/Makefile
- frontend/Makefile
When developing in a devcontainer but using the browser on the development host, the backend (`uvicorn`) and live-reload server (`ng serve`) must listen to all hosts.
> build: Listen to all hosts when running dev mode

- helm/templates/guacamole/guacd.deployment.yaml
- images/guacamole/Dockerfile
The update contains several bug fixes and stability improvements.
Release notes are available here: https://guacamole.apache.org/releases/
> [!NOTE]
> During the update of Guacamole, it will be restarted. A restart will interrupt sessions for about one minute. After the update, existing sessions will reconnect. Consider updating outside of business hours.
> build: Update Guacamole to 1.5.5

- helm/templates/sessions/guacamole.disruptionbudget.yml
- helm/templates/sessions/sessions.configmap.yaml
- helm/templates/sessions/sessions.deployment.yaml
When a user connects to a terminated or foreign session, nginx raises an 401 error, which is displayed to the user. Since it doesn't contain more information, it might be confusing. This PR adds possible reasons and solution approaches to the error message.
In addition, increase the replica for the nginx sessions router to 2 and introduce a PodDisruptionBudget to ensure that there is always one Pod available.
> feat(routing): Add redundancy and 401 error handling to session routing

- helm/config/grafana/team4capella.json
Negative values indicate failures in the metrics collection. They produce unclear jumps in the time series and influence the min and mean values.
Before:
After:
In addition, the color of the mean value was wrong. This is fixed.
> fix(monitoring): Filter out negative values

- Makefile
- README.md
- docs/docs/development/index.md
- docs/docs/development/troubleshooting.md
- docs/mkdocs.yml
To simplify the first deployment, this commit adds a new option, which pulls management portal and session images from GitHub.
Local image building is no longer required and therefore speeds up the deployment time.
The PR also contains instructions to debug issues with the reachability of the k3d registry. Related to https://github.com/DSD-DBS/capella-collab-manager/issues/1536.
> docs: Add new deployment strategy by pulling images from GitHub

- backend/Dockerfile
For some reason, the executable flag isn't preserved during `pip install`. I couldn't find the root cause for it, but this PR provides a fix by adapting the executable flag manually.
Resolves https://github.com/DSD-DBS/capella-collab-manager/issues/1618
> fix: Apply executable flag to askpass.py

- helm/templates/prometheus/prometheus.configmap.yaml
Instead, the Jupyter container has to report the idletime via an metrics endpoint.
This commit contributes to the goal of removing the Jupyter specific integration from the Collaboration Manager and replace it with abstract tool support.
Requires https://github.com/DSD-DBS/capella-dockerimages/pull/292
> fix: Remove special handling of Jupyter idletime

- backend/capellacollab/core/authentication/basic_auth.py
- backend/capellacollab/core/authentication/exceptions.py
- backend/capellacollab/core/authentication/provider/oauth/flow.py
- backend/capellacollab/core/responses.py
When the refresh token was expired, the backend sent the error "TOKEN_SIGNATURE_EXPIRED". The frontend did then request a new refresh token, leading to an infinite loop and a DDOS attack on our backend.
The error was accidentially added in #1569.
> fix: Infinite authentication loop

- backend/capellacollab/cli/openapi.py
- backend/capellacollab/cli/ws.py
- backend/tests/cli/test_workspace_backup.py
- Improve the CLI speed by only importing large modules that are required for the requested command.
- Add an log level option to set the log level via the CLI.
- Add resources for OpenShift compatibility
- Generate new clients to avoid passing the Kubernetes client via parameters.
> perf: Improve CLI speed and display options

- Makefile
The Initialization raised several errors when the corresponding tables did already exist. We ignored those errors, but they are confusing for administrators.
Therefore, skip initialization if already done.
> build: Skip initialization of Guacamole if not needed

- helm/templates/prometheus/prometheus.deployment.yaml
- helm/templates/prometheus/prometheus.volume.yaml
In addition, discard old metrics if the volume reaches the capacity limit.
> feat: Increase size of Prometheus volume

- Makefile
- ci-templates/gitlab/k8s-deploy.yml
- helm/Chart.yaml
Currently, we tag all helm releases with 1.0.0 / 0.0.0. The versions are displayed when running `helm history`.
> build: Derive helm version from Git tags

- backend/capellacollab/sessions/metrics.py
- backend/tests/test_metrics.py
Some Pods may not have labels, for example the Pods created by our CLI during the restore process.
The deployed sessions collector should not fail when it hits such a Pod. Instead, it should just ignore it.
> fix: Tolerate Pods without labels in metrics

- ci-templates/gitlab/image-builder.yml
- ci-templates/gitlab/k8s-deploy.yml
- docs/docs/admin/ci-templates/gitlab/image-builder.md
- docs/docs/admin/ci-templates/gitlab/k8s-deploy.md
- The `unencrypted` suffix was removed from the files. Instead, it's recommended to use the `encrypted_regex` configuration as described in the admin documentation
- The `general.values.yaml` and `secret.values.yaml` were merged into one encrypted file `values.yaml`. Also in this case it's recommended to use the `encrypted_regex` configuration.
- Decrypt the sops file in-memory and never write them to disk. This improves security.
> refactor!: Restructure SOPS files in Gitlab CI/CD templates

- frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.ts
> feat: Auto-select recommended version for read-only sessions

- .github/workflows/chart-release.yaml
Our Helm registry is hosted in another repository on GitHub: https://github.com/DSD-DBS/ccm-helm-charts
New releases will be added when they are added to the GitHub repository.
> ci: Push Helm charts to GH Pages Helm registry

- docs/.prettierrc.yaml
- docs/docs/admin/ci-templates/gitlab/image-builder.md
- docs/docs/admin/ci-templates/gitlab/k8s-deploy.md
- docs/docs/admin/getting_started/index.md
- docs/docs/admin/installation.md
- docs/docs/admin/settings/model-sources/git.md
- docs/docs/admin/settings/tools/index.md
- docs/docs/admin/teamforcapella/project-management/index.md
- docs/docs/admin/tools/configuration.md
- docs/docs/api/index.md
- docs/docs/development/backend/code-style.md
- docs/docs/development/docs.md
- docs/docs/development/frontend/customize.md
- docs/docs/development/frontend/responsive-design/mobile-view.md
- docs/docs/development/frontend/routes.md
- docs/docs/development/frontend/storybook.md
- docs/docs/development/frontend/testing.md
- docs/docs/development/index.md
- docs/docs/development/pull_requests.md
- docs/docs/development/troubleshooting.md
- docs/docs/index.md
- docs/docs/release-notes.md
- docs/docs/user/index.md
- docs/docs/user/projects/add-user/index.md
- docs/docs/user/projects/models/complexity_badge.md
- docs/docs/user/projects/models/create.md
- docs/docs/user/projects/models/diagrams/setup_diagram_cache.md
- docs/docs/user/sessions/jupyter/collaboration.md
- docs/docs/user/tools/capella/t4c-git-compare.md
This will fix some issues regarding the rendering of lists and seems to be more compatible with the prettier formatting.
With the change I've removed some `prettier-ignore` messages.
Fixes https://github.com/DSD-DBS/capella-collab-manager/issues/1381
See also: https://github.com/Python-Markdown/markdown/issues/3
> refactor(docs): Use indentation of 4 instead of 2

- frontend/src/app/projects/project-overview/project-overview.component.html
- frontend/src/app/projects/project-overview/project-overview.component.ts
This sorts the project cards alphabetically and adds a basic search bar to filter projects.
It partially addresses #402, but I haven't implemented project favorites yet.
> feat: Make project view searchable and sorted

- backend/capellacollab/config/models.py
- docs/docs/admin/authentication/keycloak/index.md
- helm/config/backend.yaml
- helm/values.yaml
This removes the unused `audience` configuration field. The field is not used because `authentication.client_id` is the expected audience for the issued identity tokens, so we do not need a separate field for it.
Resolves #1685
> refactor: Remove unused `audience` configuration field

- frontend/src/app/sessions/service/user-session.service.ts
- frontend/src/app/sessions/user-sessions-wrapper/user-sessions-wrapper.component.ts
This PR ensures that pending requests against the sessions endpoint are canceled when a new request is made. This improves performance when the backend is unavailable for a period of time, as it will no longer be flooded with session requests when it becomes available again.
Resolves #1134
> feat: Cancel previous sessions requests

- frontend/src/app/general/auth/auth/auth.component.html
Remove the "Open" from "Open Documentation".
> fix: Unify buttons in authentication components

- frontend/src/app/general/error-handling/error-handling.interceptor.ts
Unauthenticated redirects to the login page. It's not an error itself and should not be displayed with error message.
> fix: Hide "Unauthenticated" error in the frontend

- backend/capellacollab/sessions/hooks/__init__.py
- backend/capellacollab/sessions/hooks/networking.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/routes.py
- backend/tests/sessions/hooks/test_networking_hook.py
- backend/tests/sessions/k8s_operator/test_session_k8s_operator.py
- helm/templates/backend/backend.serviceaccount.yaml
A requirement for the training mode is that a Jupyter session can talk to a Capella session.
This PR adds network policies so that Pods can reach the ports of other Pods from the same user.
> feat: Allow communication between sessions of same user

- frontend/angular.json
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-code-block/model-diagram-code-block.component.html
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-code-block/model-diagram-code-block.component.ts
- frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-code-block/model-diagram-code-block.stories.ts
Styling of the code block was broken. See Chromatic for more details. Also, a deprecated hightlight.js function was replaced.
> fix: Update styling and deprecated `highlight.js`-method

- helm/templates/routing/routing.ingress.yaml
Due to the new authentication workflow, the headers of requests. Nginx has refused those large requests in a few cases. This commit increases the buffer size.
> fix: Update proxy buffering options on Ingress

- frontend/src/app/sessions/service/session.service.ts
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.html
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.stories.ts
Using color for the session indicator makes it more difficult to read for colorblind people.
This PR adds icons which help with quickly identifying the session state. Corresponding stories are also added to showcase the new icons.
Closes #1709
> feat: Add icons to session indicator for a11y

- backend/pyproject.toml
The fastapi-pagination package is not compatible with the latest version of fastapi:
https://github.com/uriyyo/fastapi-pagination/issues/1273
> ci: Temporarily set fastapi to `<0.112.4` due to incompatility

- backend/capellacollab/settings/modelsources/t4c/repositories/crud.py
- backend/tests/sessions/hooks/test_t4c_hook.py
When a single T4C repository was used in multiple different toolmodels, the repository was injected twice into the session in the T4C session hook.
This led to errors in the dropdown menu of the T4C connection in Capella sessions.
> fix: Use T4C repository in multiple projects / models

- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/create-session-history.component.ts
This ensures that the session history subscription is destroyed immediately after the first value is emitted. This ensures that the subscription is not executed multiple times when you leave and return to the session page.
> fix: Destroy session history subscription

- backend/Makefile
- frontend/Makefile
The host can be still set via the `HOST` environment variable. If you want to expose it to all hosts, set `HOST` to `0.0.0.0`
> build: Expose development environment on localhost only

- backend/capellacollab/__main__.py
- frontend/Makefile
The redirectURI and CORS policy would have to be modified otherwise.
> build(dev): Run frontend on `localhost` instead of `127.0.0.1`

- backend/capellacollab/settings/modelsources/t4c/crud.py
- backend/capellacollab/settings/modelsources/t4c/routes.py
- backend/tests/settings/teamforcapella/test_t4c_instances.py
- frontend/src/app/openapi/api/settings-modelsources-t4-c.service.ts
- frontend/src/app/services/settings/t4c-instance.service.ts
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.html
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.stories.ts
Resolved number 1 of https://github.com/DSD-DBS/capella-collab-manager/issues/1739
Resolves #971
> feat: Delete TeamForCapella repositories

- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/connection-dialog/connection-dialog.component.html
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/connection-dialog/connection-dialog.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/connection-dialog/connection-dialog.stories.ts
Disables the "Connect to session" button inside the connection dialog if the session's connection info is not available. The logic to show a toast when there is no session information is removed, as there is no situation where it could be triggered.
Closes #1785
> fix: Disable "Connect to session" button when missing session info

- frontend/src/app/sessions/sessions.component.html
- frontend/tailwind.config.js
On small screens, the welcome banner is unnecessary clutter. Hide it on anything that's less tall than a 1080p monitor.
Closes #1786
> fix: Hide welcome banner on small screens

- .github/workflows/push.yml
- Makefile
- README.md
- backend/capellacollab/config/models.py
- backend/capellacollab/core/logging/loki.py
- backend/capellacollab/sessions/operators/k8s.py
- helm/config/backend.yaml
- helm/templates/backend/postgres.deployment.yaml
- helm/templates/grafana/grafana.configmap.yaml
- helm/templates/guacamole/postgres.deployment.yaml
- helm/templates/promtail/_promtail.tpl
- helm/templates/valkey/valkey.secret.yaml
- helm/values.yaml
To avoid unintential default secrets in production, passwords default to null now. `helm upgrade` will fail if the secrets are not set.
> build: Fail `helm upgrade` if secrets are not set in `values.yaml`

- backend/capellacollab/feedback/models.py
- frontend/src/app/app.component.ts
- frontend/src/app/openapi/model/feedback-rating.ts
Fix a bug where the interval feedback prompt would be shown, even when the user is not logged in. Restore the original order of the feedback buttons by changing the server-side enum.
> fix: Disable Feedback Prompt when logged out, Change order of buttons

- frontend/src/app/app.component.ts
- frontend/src/app/general/auth/auth-redirect/auth-redirect.component.ts
- frontend/src/app/sessions/feedback/feedback.service.ts
As a result of https://github.com/DSD-DBS/capella-collab-manager/pull/1828, the feedback interval doesn't trigger the dialog anymore after login, only after refresh if logged in. This can be an issue for users which don't use the CCM often since they have to login each time. This PR makes sure that the dialog is also triggered after login.
Also fixes another bug that the request to the backend was triggered twice.
> feat: Trigger feedback dialog after login

- frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.stories.ts
- frontend/src/app/settings/modelsources/git-settings/add-git-instance/add-git-instance.component.html
The mat-error animation didn't complete for an invalid input of the ManageGitModelComponent.
> test: Add delay to let mat-error animation complete

- backend/capellacollab/__main__.py
Internal server error respones result in no CORS ALLOW_ORIGIN headers added to the response. This leads to wrong handling by the frontend. When there are no CORS headers, status code was 0, which was treated as "Backend not reachable".
There was already handling to add CORS headers, but it didn't add the ALLOW_ORIGIN header, which we add manually now.
> fix: Add CORS Headers to HTTP error 500 responses

- frontend/Makefile
When I don't invoke the Storybook command via npm, it fails with: 
```
An unhandled exception occurred: Unable to find a usable package manager within NPM, PNPM, Yarn and Yarn 2
```
> build: Fix a bug that Storybook couldn't recognize npm

- helm/config/grafana/dashboards/active-sessions.json
By default, it did only choose one tool version, one connection method and one session type. Instead, add an "All" option and set it as default to display the page without filters when loading initially.
> feat(grafana): Show all active sessions by default, disable filters

- backend/capellacollab/sessions/routes.py
- backend/tests/sessions/test_session_routes.py
- frontend/src/app/openapi/api/sessions.service.ts
- helm/templates/sessions/sessions.configmap.yaml
The new 401 error page: 
The new 502 error page: 
This also fixes a bug that an "500 - Internal server error" page was displayed when the user tried to access a session without session token.
> feat: Make nginx error pages more user-friendly

- helm/templates/routing/routing.ingress.yaml
- helm/templates/routing/sessions.ingress.yaml
The default timeout for nginx is 60 seconds and for haproxy it's 30 seconds. Our session proxy should terminate requests after 60 seconds with a custom error page, but the Ingress nginx / HAProxy was faster.
This sets the timeout to 70s, independently from nginx / HAProxy.
> feat: Let session proxy handle timeouts

- docs/mkdocs.yml
> docs: Remove reference to "API documentation" from navbar

- docs/docs/admin/teamforcapella/migration.md
Since we introduced the strict version validation, the previous order didn't work anymore.
> docs: Change order of TeamForCapella model migration steps

- backend/capellacollab/core/authentication/oidc.py
- backend/capellacollab/sessions/injection.py
- backend/capellacollab/sessions/operators/k8s.py
- Refresh token failure was promoted to INFO
- Session metric not found was reduced to DEBUG
- Not found deployment don't raise an exception / log message anymore
> refactor: Tune log levels

- frontend/src/app/general/auth/auth-guard/auth-guard.service.ts
- frontend/src/app/general/auth/auth-redirect/auth-redirect.component.ts
- frontend/src/app/general/auth/auth/auth.component.html
- frontend/src/app/general/auth/auth/auth.component.ts
- frontend/src/app/general/auth/http-interceptor/auth.interceptor.ts
- frontend/src/app/services/auth/auth.service.ts
On initial login, the URL was already preserved.
When the login was triggered by an expired token while working in the application, the user was always redirect to the start page after login.
To prevent interruption of workflows, the user is redirected to the original page again.
> feat: Redirect to open page after login again

- backend/capellacollab/sessions/operators/k8s.py
- frontend/src/app/sessions/service/session.service.ts
Previously, it did only fall back to "Unknown" state. This commit adds explicit handling for it.
> feat: Add "Session container not found" sessions tatus

- Makefile
Simplifies the dev-experience since it's no longer required to have the helm chart deployed.
> build: Create sessions namespace in cluster creation target

- helm/config/grafana/dashboards/team4capella.json
We iterate over license servers anyway and there shouldn't be too many
> chore: Disable filtering for license servers in Grafana dashboard

- backend/capellacollab/core/database/migration.py
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
- frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.stories.ts
- Capella version and license server are now set properly while editing.
- Some stories have been improved.
- The REST API is not experimental anymore; the corresponding text has been removed.
> fix: Minor frontend fixes for T4C instance components

- frontend/src/app/general/auth/auth-redirect/auth-redirect.component.ts
If the redirect is set to one of those URLs, just redirect to the start page. Otherwise this will create a redirect loop since the user is logged out after login.
Also improves security by removing the query params from the callback URL while the token request is in progress.
> fix: Don't loop-redirect to `/auth` or `/logout`

- backend/capellacollab/feedback/routes.py
- backend/capellacollab/feedback/util.py
Feedback emails are sent in a background task to decrease response latency. Unfortunately, this means that the SQLAlchemy session is already closed and none of the fields of DatabaseUser can be resolved. This bug was not found because the error messages are swallowed by the background task. The bug is fixed by turning the DatabaseUser object into a normal User object before passing it to the background task.
> fix: Fix an issue where feedback that shared contact info was not sent

- helm/config/grafana/dashboards/feedback.json
In a previous commit, a handling for metrics without the anonymous label was added. This leads to issues when all metrics have the anonymous label. In this case, Grafana showed "No data".
> fix(grafana): Add fallback if all feedback values have anonymous label

- backend/capellacollab/core/database/__init__.py
Due to the asynchronous nature of FastAPI and the number of requests, it can happen that we have to handle more than the default of 5 requests at the same time.
In addition, reduce the pool timeout to 5. The goal is to fail requests if they can't get a database session within 5 seconds instead of spawning a queue with wait times of 30 seconds, which can lead to a blocking backend.
Resolves #1914
> fix: Increase connection pool to 20 concurrent database connections

- backend/capellacollab/__main__.py
- backend/capellacollab/core/database/metrics.py
- backend/capellacollab/metrics.py
- backend/tests/core/test_database_metrics.py
Adds the following to the `/metrics` endpoint: 
```
sqlalchemy_pool_size 20.0
sqlalchemy_connections_in_pool 1.0
sqlalchemy_pool_overflow -19.0
sqlalchemy_checked_out_connections 0.0
```
> feat: Add metrics about the SQLAlchemy database pool

- .pre-commit-config.yaml
- Makefile
- backend/Makefile
- backend/capellacollab/__main__.py
- backend/capellacollab/alembic/versions/7683b08b00ba_add_environment_and_connection_info_to_.py
- backend/capellacollab/cli/__main__.py
- backend/capellacollab/cli/keys.py
- backend/capellacollab/core/__init__.py
- backend/capellacollab/core/database/migration.py
- backend/capellacollab/sessions/auth.py
- backend/capellacollab/sessions/hooks/__init__.py
- backend/capellacollab/sessions/hooks/authentication.py
- backend/capellacollab/sessions/hooks/http.py
- backend/capellacollab/sessions/injection.py
- backend/capellacollab/sessions/routes.py
- backend/pyproject.toml
- backend/tests/cli/test_cli.py
- backend/tests/cli/test_keys.py
- backend/tests/sessions/hooks/test_http_hook.py
- backend/tests/sessions/hooks/test_pre_authentiation_hook.py
- backend/tests/sessions/test_session_auth.py
- backend/tests/sessions/test_session_injection.py
- backend/tests/sessions/test_session_routes.py
- backend/tests/sessions/test_session_sharing.py
- docs/docs/development/index.md
- helm/templates/backend/backend-data.volume.yaml
- helm/templates/backend/backend.deployment.yaml
Instead of the non-structured session token, issue a nested JWT containing `session.id`, `user.id`, `user.name`, `user.email `and `user.role`. More claims will be added in the future.
During session connection, the backend issues a signed JWT token. The private key is auto-generated in the backend (if it doesn't exist) and can be exchanged via new CLI endpoints.
The JWT is validated automatically for all requests to HTTP-based sessions. The JWT can be read from the `ccm_session_token` cookie and can be trusted by sessions. It may be used to extract user or session information in the sessions itself.
The validate_token endpoint doesn't require an active database session anymore, reducing network traffic and improving the response times. This effectively makes sessions slightly faster.
One …
> feat!: Issue JWT for session pre-authentication

- helm/config/grafana/dashboards/feedback.json
Otherwise, the period under consideration changes if the time range changes in the UI.
This led to different user happiness index values at the same time when different time ranges were selected.
> feat(grafana): Always use 7d range for user happiness index chart

- frontend/src/app/projects/project-overview/project-overview.component.html
- frontend/src/app/projects/project-overview/project-overview.component.ts
Add the ability to show only projects or only trainings in the project view.
Closes #1821
> feat: Add the ability to filter trainings in project view

- frontend/src/app/projects/project-overview/project-overview.component.html
- frontend/src/app/projects/project-overview/project-overview.component.ts
> feat: Add the ability to filter project privacy in project view

- backend/capellacollab/tools/models.py
Before, the redirect_url was hardcoded to `http://localhost:8080`.
> fix: Add correct default for redirect_url when adding a new tool

- backend/capellacollab/feedback/models.py
- frontend/src/app/sessions/feedback/feedback-dialog/feedback-dialog.component.html
- frontend/src/app/sessions/feedback/feedback-dialog/feedback-dialog.component.ts
The previous limit of 255 was a bit too short, so raise it to 500. Add a client-side warning about the feedback being too long instead of making users run into a server-side error.
> fix: Allow longer feedback and warn users if their feedback is too long

- .github/workflows/openapi.yml
- .pre-commit-config.yaml
- backend/capellacollab/__main__.py
- backend/capellacollab/config/models.py
- backend/pyproject.toml
- docs/docs/development/backend/profiling.md
- docs/mkdocs.yml
It generates an HTML report to better identify slow actions in routes.
> perf: Add profiling option for backend routes

- backend/capellacollab/projects/models.py
- backend/capellacollab/projects/routes.py
- frontend/src/app/openapi/model/post-project-request.ts
- frontend/src/app/projects/create-project/create-project.component.html
- frontend/src/app/projects/create-project/create-project.component.ts
- frontend/src/app/projects/service/project.service.ts
- frontend/src/storybook/project.ts
> feat: Allow setting project type during creation

- backend/capellacollab/core/database/migration.py
- backend/capellacollab/projects/toolmodels/backups/exceptions.py
In addtion, set the default T4C Server Version to 6.0.0.
> chore: Improve error message for failed pipeline operation

- frontend/src/app/sessions/sessions.component.html
The margin was on the welcome-card before. Since the welcome card is hidden on small screens, the margin wasn't applied on those screens.
> chore: Add small margin to main page on small screens

- backend/capellacollab/sessions/operators/k8s.py
`status.container_statuses` can be `None`. In this case, return `UNKNOWN` as status.
> fix: Handle case where container_statuses is `None`

- backend/capellacollab/alembic/versions/320c5b39c509_add_beta_tester.py
The migration was wrong, leading to an invalid configuration.
> fix: Replace 'default' with 'regular' image in alebmic migration

- backend/capellacollab/sessions/hooks/__init__.py
- backend/capellacollab/sessions/hooks/interface.py
- backend/capellacollab/sessions/hooks/log_collector.py
- backend/capellacollab/sessions/hooks/networking.py
- backend/capellacollab/sessions/metrics.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/operators/models.py
- backend/capellacollab/sessions/routes.py
- backend/tests/sessions/k8s_operator/test_session_k8s_operator.py
- backend/tests/sessions/k8s_operator/test_session_state.py
> fix: Move promtail container to external Pod

- .pre-commit-config.yaml
- backend/tests/projects/test_projects_users_routes.py
- backend/tests/test_event_creation.py
- backend/tests/users/fixtures.py
Leads to better correctness according to the pylint docs.
> ci: Add `require_serial` to pylint pre-commit

- backend/capellacollab/sessions/hooks/__init__.py
- backend/capellacollab/sessions/hooks/authentication.py
- backend/capellacollab/sessions/hooks/guacamole.py
- backend/capellacollab/sessions/hooks/http.py
- backend/capellacollab/sessions/hooks/interface.py
- backend/capellacollab/sessions/hooks/jupyter.py
- backend/capellacollab/sessions/hooks/log_collector.py
- backend/capellacollab/sessions/hooks/networking.py
- backend/capellacollab/sessions/hooks/persistent_workspace.py
- backend/capellacollab/sessions/hooks/provisioning.py
- backend/capellacollab/sessions/hooks/pure_variants.py
- backend/capellacollab/sessions/hooks/read_only_workspace.py
- backend/capellacollab/sessions/hooks/session_preparation.py
- backend/capellacollab/sessions/hooks/t4c.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/sessions/util.py
- backend/tests/sessions/hooks/conftest.py
- backend/tests/sessions/hooks/test_guacamole_hook.py
- backend/tests/sessions/hooks/test_http_hook.py
- backend/tests/sessions/hooks/test_jupyter_hook.py
- backend/tests/sessions/hooks/test_networking_hook.py
- backend/tests/sessions/hooks/test_persistent_workspace.py
- backend/tests/sessions/hooks/test_pre_authentiation_hook.py
- backend/tests/sessions/hooks/test_provisioning_hook.py
- backend/tests/sessions/hooks/test_pure_variants.py
- backend/tests/sessions/hooks/test_session_preparation.py
- backend/tests/sessions/hooks/test_t4c_hook.py
- backend/tests/sessions/test_session_hooks.py
- backend/tests/sessions/test_session_routes.py
This makes it easier in the future to extend the requests and allows better type annotations.
> refactor: Consolidate session hook request arguments into one

- backend/pyproject.toml
`aiohttp` released a version that breaks aioresponses. Until the coresponding PR is merged on their side, stick to aiohttp < 3.11.0
More information: https://github.com/pnuckowski/aioresponses/issues/263
> chore: Limit version of `aiohttp`

- backend/Makefile
- backend/capellacollab/core/database/migration.py
- backend/tests/settings/teamforcapella/test_t4c_instances.py
- backend/tests/settings/teamforcapella/test_t4c_license_servers.py
- backend/tests/settings/test_git_instances.py
In addition, add GitLab as additional Git instance.
> chore: Add TeamForCapella cluster instance by default

- backend/capellacollab/settings/configuration/models.py
- backend/tests/test_feedback.py
- docs/docs/admin/configure-for-your-org.md
- frontend/src/app/openapi/model/feedback-configuration-input.ts
- frontend/src/app/openapi/model/feedback-configuration-output.ts
- frontend/src/app/sessions/feedback/feedback-dialog/feedback-dialog.component.html
- frontend/src/app/sessions/feedback/feedback-dialog/feedback-dialog.stories.ts
- frontend/src/storybook/feedback.ts
- Allow customizing the hint text.
- Always show the text input to prevent layout shift
- Enable dynamic sizing for hint to prevent layout issues
> feat: Allow customizing feedback hint and update dialog

- frontend/src/app/sessions/session/session-viewer.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.html
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.ts
Remove the floating window manager and redesign some of the surrounding UI.
Closes #2011
> feat: Remove floating window manager

- frontend/src/app/general/notice/notice.component.ts
The warning class of the notice component interfered with the session iframe, resulting in black text in the status message of the session.
> fix: Enable view encapsulation for notice component

- backend/capellacollab/sessions/injection.py
Prometheus returns floats as strings, e.g., `"16.5"` is a valid idletime. This breaks the `int()` parsing since it can't handle floats as strings.
> fix: Convert Prometheus floating point numbers correctly to int

- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.component.html
> feat: Move terminate button to end of session card

- frontend/src/app/general/relative-time/relative-time.component.ts
- frontend/src/app/sessions/session-overview/session-overview.component.html
- frontend/src/app/sessions/session-overview/session-overview.stories.ts
- Don't show seconds on last seen
- Make creation date relative
- Fix Story not having mock date
> feat: Don't show seconds on last seen and make creation time relative

- helm/templates/routing/routing.ingress.yaml
If nginx was used as Ingress, the default max body size of 1MB was applied. This has blocked uploads of files > 1MB.
> fix: No longer block uploads of larger files in Ingress nginx

- frontend/src/app/sessions/session/floating-window-manager/floating-window-manager.component.html
- frontend/src/app/sessions/session/floating-window-manager/floating-window-manager.component.ts
- frontend/src/app/sessions/session/session-viewer.service.ts
- frontend/src/app/sessions/session/session-viewer.stories.ts
- frontend/src/app/sessions/session/tiling-window-manager/tiling-window-manager.component.html
- frontend/src/app/sessions/session/tiling-window-manager/tiling-window-manager.component.ts
> feat: Allow users to copy t4c token from session viewer

- backend/capellacollab/sessions/injection.py
- backend/tests/sessions/test_session_injection.py
"Unknown session" could be interpreted as "The session doesn't exist", but that is not true. The session exists and only the metrics are not available.
> chore: Change idle time unavailable message if metrics not found

- backend/capellacollab/configuration/app/models.py
- backend/capellacollab/core/database/migration.py
- helm/config/backend.yaml
During database initialization, add the Capella Model Explorer as tool.
> feat: Add Capella Model Explorer as default tool

- backend/capellacollab/feedback/models.py
- backend/tests/test_feedback.py
- frontend/src/app/openapi/model/anonymized-session.ts
- frontend/src/app/sessions/session/session-viewer.stories.ts
The preparation state was not part of the email, only the state.
> feat: Add `preparation_state` to feedback email

- backend/capellacollab/configuration/app/models.py
- backend/capellacollab/sessions/models.py
- backend/capellacollab/sessions/util.py
- docs/docs/admin/tools/configuration.md
- frontend/src/app/openapi/model/session.ts
- frontend/src/storybook/session.ts
- helm/config/backend.yaml
- helm/templates/backend/backend.networkpolicy.yaml
The internal endpoints can be received via the API for inter-session communication.
A new network route is available between sessions and the backend. This enables sessions to use the backend API.
Two new pre-defined variables were added:
- `CAPELLACOLLAB_API_BASE_URL`
- `CAPELLACOLLAB_SESSION_REQUESTER_USER_ID`
This enables sessions to talk to other sessions more easily. For example, this is a small script to send a request to another session. The personal access token has to be replaced manually (until #1774 is implemeted). 
```py
import os
import requests
backend_url = os.getenv("CAPELLACOLLAB_API_BASE_URL")
user_id = os.getenv("CAPELLACOLLAB_SESSION_REQUESTER_USER_ID")
username = os.getenv("CAPELLACOLLAB_SESSION_REQUESTER_USERNAME")
response = …
```
> feat: Add internal endpoints for sessions and expose backend

- backend/capellacollab/core/database/migration.py
Jupyter greeted users with "404 - Not found" in the local setup. This PR fixes the issue.
> fix: Add CORS for local Jupyter setup

- .github/workflows/storybook-diff.yml
There is another error with v2 (`Error: Cannot copy __reg__/0_diff/General components_404 (Not Found)_Not Found_desktop.png: the file doesn't exist`), but at least the report in generated in the artifacts and can be downloaded. 
Check this issue for more information about the v3 issue: https://github.com/reg-viz/reg-actions/issues/178
> ci: Downgrade to reg-actions v2

- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-readonly-session/create-readonly-model-options/create-readonly-model-options.component.html
Rename "Deep clone" to "Include change history"
> feat: Improve clarity of "Deep clone" button for read-only sessions

- .github/workflows/storybook-diff.yml
- .github/workflows/storybook-publish.yml
- frontend/src/app/general/404/404.stories.ts
We've had issues with storybook diff captures timing out due to the long startup time of storybook. By building storybook first, then running storycap on the static build output, we can avoid these timeouts.
> ci: Build storybook for diffing

- frontend/src/app/projects/project-detail/project-users/service/project-user.service.ts
When changing the project from a project with project admin privileges to a project without project admin permissions, it still tried to load the project users, which led to an error.
> feat: Fix loading of project users on project change

- backend/capellacollab/sessions/files/exceptions.py
- backend/capellacollab/sessions/files/routes.py
- backend/capellacollab/sessions/operators/k8s.py
- frontend/src/app/openapi/api/sessions.service.ts
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/file-browser-dialog/file-browser-dialog.component.html
- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/file-browser-dialog/file-browser-dialog.component.ts
> feat: Delete files in file browser

- backend/Dockerfile
- backend/startup.sh
Use `uv` for the Python installation in the backend Docker image. This restores compatibility with the debian:bookworm-slim image, which was used in the Gitlab CI template.
> build: Use `uv` for Python installation in backend Docker image

- frontend/nginx.conf
Assets inside the /assets/ folder are immutable, so they can be cached by browsers forever to increase performance.
Closes #2141
> feat: Set Cache-Control header on static assets

- frontend/package-lock.json
- frontend/package.json
- @analogjs/content is used for content routes which we don't have
- prismjs is used for content routes and to highlight code in ngx-markdown (which we don't do)
- semver is not used
- We don't have any tests using Vitest
- vite-plugin-checker isn't used anywhere
> build: Remove useless dependencies

- frontend/nginx.conf
We removed the application/javascript filetype because it's considered legacy. Unfortunately, nginx uses it to decide if it should compress .js files so they weren't being compressed.
> fix: Make sure gzip is applied to js files

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/app-routing.module.ts
- frontend/src/app/helpers/editor/editor.component.html
- frontend/src/app/helpers/editor/editor.component.ts
- frontend/src/app/settings/core/configuration-settings/configuration-settings.component.html
- frontend/src/app/settings/core/configuration-settings/configuration-settings.component.ts
- frontend/src/app/settings/core/tools-settings/create-tool/create-tool.component.html
- frontend/src/app/settings/core/tools-settings/create-tool/create-tool.component.ts
- frontend/src/app/settings/core/tools-settings/tool-details/tool-details.component.html
- frontend/src/app/settings/core/tools-settings/tool-details/tool-details.component.ts
- frontend/src/app/settings/core/tools-settings/tool-details/tool-nature/tool-nature.component.html
- frontend/src/app/settings/core/tools-settings/tool-details/tool-nature/tool-nature.component.ts
- frontend/src/app/settings/core/tools-settings/tool-details/tool-version/tool-version.component.html
- frontend/src/app/settings/core/tools-settings/tool-details/tool-version/tool-version.component.ts
- frontend/src/app/yaml.worker.js
- frontend/src/styles.css
- frontend/vite.config.ts
Until now, we were importing Monaco directly which massively increased our bundle size. By moving to
ngx-monaco-editor-v2, Monaco is loaded on-demand. Also add support for monaco-yaml, which provides
Intellisense for our yaml configs using OpenAPI schemas. This is also our first component using
signals.
Closes #2089
> feat: Rework Monaco editor integration

- frontend/src/app/projects/project-detail/model-overview/model-overview.component.html
- frontend/src/app/projects/project-detail/model-overview/model-overview.component.ts
- frontend/src/app/projects/project-detail/model-overview/model-overview.stories.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session-dialog/create-persistent-session-dialog.component.html
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session-dialog/create-persistent-session-dialog.component.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session-dialog/create-persistent-session-dialog.stories.ts
Re-order the buttons on the model card, moving some infrequently used ones to an overflow menu. Modify the "Create Persistent Session" button to prompt for the connection method and then immediately create the session.
Closes #1353
> feat: Redesign Model Card

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/session-history.service.ts
Use Zod for validating the session history from localStorage. This is simpler and less error-prone than doing it manually, and also prepares us for implementing more features built on storing data in localStorage (like favorites).
> refactor: Use Zod for Session History

- .github/dependabot.yml
Even though we use `pnpm`, the value has to be `npm` as per docs
> ci: Change `pnpm` to `npm` in dependabot configuration

- frontend/package.json
This reverts parts of commit 4f9979a8864e81e77f24e6063f5407594262cede.
Puppeteer doesn't work with pnpm 10.
> build: Downgrade pnpm

- frontend/src/app/sessions/user-sessions-wrapper/active-sessions/session-card/session-card.component.html
The shown seconds were not accurate.
Show minutes instead.
> fix: Don't show seconds for estimated session termination

- backend/capellacollab/alembic/versions/16a64401737c_add_uniqueness_constraint_for_project_.py
- backend/capellacollab/projects/crud.py
- backend/capellacollab/projects/models.py
- backend/capellacollab/projects/permissions/permissions.py
- backend/capellacollab/projects/users/crud.py
- backend/capellacollab/projects/users/models.py
- backend/capellacollab/projects/users/routes.py
- backend/capellacollab/settings/modelsources/t4c/instance/repositories/crud.py
- backend/capellacollab/users/models.py
- backend/tests/projects/test_projects_permissions.py
- backend/tests/projects/test_projects_users_routes.py
- backend/tests/projects/toolmodels/pipelines/pipeline-runs/conftest.py
- backend/tests/projects/toolmodels/test_toolmodel_routes.py
- backend/tests/projects/users/fixtures.py
- backend/tests/sessions/hooks/test_t4c_hook.py
- backend/tests/users/test_tokens.py
_It's weird._ 
In our production database the primary key for the `project_user_association` table was missing. In addition, the check to add users twice didn't work. This led to users being added multiple times to projects. This PR fixes the mess.
> fix: Add uniqueness constraint for project users

- docs/copyright_hook.py
- docs/mkdocs.yml
This is also nice because it means the copyright will always be the year when the image was last re-built.
Closes #2188
> fix: Fix issue with copyright in docs when navigating

- .github/workflows/storybook-diff.yml
We thought the issue is fixed, but the pipeline still fails sporadically.
> ci: Downgrade reg-actions to v2 (again)

- images/session-preparation/clone_repositories.py
During session provisioning, the original path was removed if a backup path did exist. Instead, the backup path should have been replaced with the original path.
> fix(session-preparation): Remove backup path instead of origin path

- .github/workflows/lint.yml
- .github/workflows/openapi.yml
- .github/workflows/tests.yml
It doesn't work properly, frequently we have failing pipelines due to errors in the "Post Install Python" step, which is out of our control.
> ci: Disable caching of pip-dependencies

- .github/workflows/storybook-diff.yml
- frontend/src/app/helpers/skeleton-loaders/mat-card-overview-skeleton-loader/mat-card-overview-skeleton-loader.component.html
- frontend/src/app/helpers/skeleton-loaders/mat-card-overview-skeleton-loader/mat-card-overview-skeleton-loader.component.ts
On mobile devices, the mat-card-overview-skeleton-loader was not displayed.
Resolves https://github.com/DSD-DBS/capella-collab-manager/issues/1814
> fix: Always show at least one skeleton loader

- backend/Makefile
- backend/capellacollab/core/email/send.py
- backend/capellacollab/feedback/email.jinja
- backend/capellacollab/feedback/util.py
- backend/pyproject.toml
- helm/config/grafana/dashboards/active-sessions.json
- helm/config/grafana/dashboards/individual-session.json
- helm/config/grafana/dashboards/individual-session.json.license
The new dashboard bundles all session-related metrics in a central place. Enter a session ID and see all metrics for a specific session.
A link to the Grafana dashboard is added to the feedback URL.
> feat: Add new dashboard to see metrics for a specific session

- backend/tests/projects/test_projects_routes.py
- backend/tests/projects/test_projects_users_routes.py
- backend/tests/projects/toolmodels/pipelines/pipeline-runs/test_pipeline_runs.py
- backend/tests/projects/toolmodels/test_toolmodel_routes.py
- backend/tests/settings/teamforcapella/test_t4c_instances.py
- backend/tests/settings/teamforcapella/test_t4c_license_servers.py
- backend/tests/settings/test_global_configuration.py
- backend/tests/test_event_creation.py
- backend/tests/users/test_users.py
Some uses remain where I wasn't sure, plus alerts because those got reworked anyway.
Closes #2159
> chore: Replace usages of executor_name fixture with user/admin fixture

- backend/capellacollab/__main__.py
- backend/capellacollab/redirects.py
- helm/config/nginx-grafana.conf
- helm/config/nginx-prometheus.conf
The full URL is passed to the redirectTo query parameter in the frontend. If the full URL contains a `&`, it was treated as additional argument.
nginx doesn't provide the option to URLencode out of the box. Therefore, a small helper has been added to the backend.
> fix: Encode query parameters in Grafana & Prometheus auth redirects

- .github/codecov.yml
When a patch coverage is not met, but we decide that it's sufficient and merge the PR, the check fails on main. This will be avoided with this commit.
> ci: Run Codecov on pull requests only

- helm/config/grafana/alerting/rules.yaml
Prometheus can become unavailable due to updates, restarts, etc. Since we don't consider it as essential component, this is normal behaviour. No longer send alerts if Prometheus is not reachable.
> fix(monitoring): Tolerate unavailable data sources

- Makefile
Instead of pushing all tags, only push the relevant ones.
> build: Only push relevant tags to Docker registry

- frontend/src/app/sessions/session-overview/session-overview.component.html
- frontend/src/app/sessions/session-overview/session-overview.component.ts
> feat: Add various action buttons to the session overview table

- backend/capellacollab/sessions/hooks/interface.py
- backend/capellacollab/sessions/hooks/t4c.py
- backend/capellacollab/sessions/idletimeout.py
- backend/capellacollab/sessions/routes.py
- backend/capellacollab/sessions/util.py
- backend/tests/sessions/hooks/conftest.py
- backend/tests/sessions/hooks/test_t4c_hook.py
- backend/tests/sessions/test_session_hooks.py
Instead of evaluating the repository list during termination again, save the repositories with issued tokens in the database and revoke the tokens for exactly the same repositories.
> fix: Revoke T4C session tokens for initial repositories

- helm/Chart.lock
- helm/Chart.yaml
- helm/config/backend.yaml
- helm/config/grafana/dashboards/management-portal-logs.json
- helm/config/grafana/dashboards/management-portal-logs.json.license
- helm/templates/grafana/grafana.configmap.yaml
- helm/templates/promtail/_promtail.tpl
- helm/values.yaml
> [!IMPORTANT]
> Due to a switch in the Grafana Loki schema to TSDB, existing logs may longer be readable after the update. If you still need access to those logs, export them before the update.
In addition, add a dashboard for backend and frontend logs and prune old data sources.
> build: Bump Grafana Loki to latest Helm Chart

- Makefile
- backend/capellacollab/configuration/app/models.py
- backend/capellacollab/sessions/hooks/jupyter.py
- backend/capellacollab/sessions/hooks/log_collector.py
- backend/capellacollab/sessions/hooks/persistent_workspace.py
- backend/capellacollab/sessions/hooks/pure_variants.py
- backend/capellacollab/sessions/hooks/read_only_workspace.py
- backend/capellacollab/sessions/hooks/session_preparation.py
- backend/capellacollab/sessions/operators/k8s.py
- backend/capellacollab/sessions/operators/models.py
- backend/capellacollab/tools/models.py
- backend/tests/sessions/k8s_operator/test_session_volume_mapping.py
- backend/tests/sessions/test_session_injection.py
- frontend/src/app/openapi/model/logging-configuration-input.ts
- frontend/src/app/openapi/model/logging-configuration-output.ts
- frontend/src/storybook/tool.ts
- helm/config/grafana/dashboards/individual-session.json
- helm/config/grafana/dashboards/management-portal-logs.json
- helm/templates/sessions/session-logs.volume.yaml
Logs are collected from `/var/log/session` instead of the custom paths. This enabled better separation between logs for specific sessions. Also enables support for logs in read-only sessions.
Requires https://github.com/DSD-DBS/capella-dockerimages/pull/386 for continuous log collection.
> feat!: Collect logs per session individually

- frontend/src/app/sessions/session-overview/session-overview.component.html
- frontend/src/app/sessions/session-overview/session-overview.component.ts
- frontend/src/app/sessions/session-overview/session-overview.stories.ts
Remove the checkbox for terminating multiple sessions, shorten some table headers, and combine some columns. This should prevent ugly overflows.
> fix: Clean up overview table to prevent overflows

- helm/templates/prometheus/prometheus.deployment.yaml
Longer queries in Grafana fail with the current resources
> fix: Increase Prometheus resources

- backend/capellacollab/configuration/models.py
- backend/pyproject.toml
Our custom validator used zoneinfo to load the list of timezones every time. The python docs say this is bad for performance, and from some profiling it looks like this was taking a decent amount of time. The official validator seems to cache the list and performs a lot better.
> perf: Replace custom timezone validation with official one

- helm/templates/frontend/frontend.deployment.yaml
They were reduced because usually the frontend doesn't need much resources. However, there are some spikes (hard to measure) which slow down gzip compression.
> perf: Increase frontend resources

- helm/values.yaml
It was not changed even though it was stated so in the docs.
> fix: Revert to old image registry format for Grafana Loki

- frontend/src/app/projects/project-detail/project-details.component.html
Before, it was only available to beta-users.
The session provisioning is hidden for now; in many projects too many sessions would have been spawned.
> feat: Make training mode available for everyone

- frontend/src/app/sessions/session-overview/session-overview.component.html
- frontend/src/app/sessions/session-overview/session-overview.stories.ts
Disable it with a tooltip if session sharing is not enabled
> feat: Always show session overview sharing button

- frontend/src/app/sessions/session/session-iframe/session-iframe.component.html
- frontend/src/app/sessions/session/session-iframe/session-iframe.component.ts
- frontend/src/app/sessions/session/tiling-window-manager/tiling-window-manager.component.html
In fullscreen-mode, the white border looked strange, esp. with applications running in dark mode.
> fix: Disable session viewer border in fullscreen-mode

- backend/capellacollab/projects/crud.py
- backend/capellacollab/projects/exceptions.py
- backend/capellacollab/projects/routes.py
- backend/capellacollab/projects/toolmodels/crud.py
- backend/capellacollab/projects/toolmodels/routes.py
- backend/tests/projects/test_projects_routes.py
- backend/tests/projects/toolmodels/test_toolmodel_routes.py
- frontend/src/app/openapi/api/projects-models.service.ts
- frontend/src/app/openapi/api/projects.service.ts
- frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.html
- frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.ts
Before, the slug was auto-updated when the name of a project or tool model was changed. However, the relevance of the slug grew over time and a change can break many parts, in particual:
- The slugs are used for the file-paths of the training provisioning
- The slugs are used as unique identifier for the API; existing script may break after an update.
It's indended to add another feature to update the slug individually in the future. Until then, a new project can be created and all models can be moved to the new project.
> feat: Make slugs of projects and tool models immutable

- frontend/src/styles.scss
A new background color was introduced with Material 3, but it doesn't fit in our design. Let's remove it again.
> fix: Clear background color for mat-trees

- backend/pyproject.toml
- frontend/src/app/settings/core/tags/tags.component.html
https://github.com/fastapi/typer/discussions/1215
> fix: Pin click to '<8.2.0' due to incompatible breaking change

- backend/pyproject.toml
This reverts commit 4586d6f8efa1294643514a12cbfac54e725bffa2.
No longer needed, fixed by https://github.com/fastapi/typer/releases/tag/0.15.4
> Revert "fix: Pin click to '<8.2.0' due to incompatible breaking change"

- backend/capellacollab/projects/toolmodels/diagrams/routes.py
When diagram cache responses have a valid job id, responses will not change in the future. This means they can be cached at the browser level. This does not yet include any potential changes to the way diagrams are actually loaded in the diagram cache viewer.
> feat: Set cache headers on diagram cache responses

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/app/general/announcement/announcement.service.ts
- frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/session-history.service.ts
My original plan was to migrate this project to Zod v4 mini (which has a similarly small bundle size), but as this requires certain tsconfig options that don't work with Angular, I decided to replace Zod with Valibot. This also fixes a bug where an invalid session history would be permanently corrupted instead of automatically resetting itself.
> refactor: Use Valibot instead of Zod to decrease bundle size
