DSD-DBS/capella-collab-manager

frontend/src/app/active-sessions/active-sessions.component.html, frontend/src/app/active-sessions/active-sessions.component.ts
=> Disable reconnect button as long as session has not started

Makefile, README.md, dashboard/dashboard.rolebinding.yml, dashboard/dashboard.serviceaccount.yml, helm/templates/backend/backend.deployment.yaml, helm/templates/backend/postgres.deployment.yaml, helm/templates/docs/docs.deployment.yaml, helm/templates/frontend/frontend.deployment.yaml, helm/templates/guacamole/guacamole.deployment.yaml, helm/templates/guacamole/guacd.deployment.yaml, helm/templates/guacamole/postgres.deployment.yaml, helm/templates/mock/licence.deployment.yaml, helm/templates/mock/nginx.deployment.yaml, helm/templates/mock/oauth.deployment.yaml, helm/templates/mock/t4c.deployment.yaml, helm/templates/prometheus/nginx.deployment.yaml, helm/templates/prometheus/prometheus.deployment.yaml, helm/templates/routing/nginx.deployment.yaml
This PR improves the local performance on devices with low resources. There is now a separate resource definition for local deployment. 
In addition, there is a new goal for `make` to run the kubernetes dashboard. 
Run `make dashboard` to see and test the local dashboard.
Run `make deploy` to test the local resources. All containers were still in the running state.
=> Local performance

backend/capellacollab/core/authentication/database/__init__.py, backend/capellacollab/core/authentication/database/jenkins.py, backend/capellacollab/core/authentication/jwt_bearer.py, backend/capellacollab/projects/users/routes.py, backend/capellacollab/routes/users.py, backend/capellacollab/sessions/files/routes.py, backend/capellacollab/sessions/routes.py, backend/capellacollab/settings/modelsources/git/routes.py, backend/capellacollab/utils/git_utils.py, frontend/src/app/auth/http-interceptor/auth.interceptor.ts
Update `HTTPException` structure to automatically display legacy backend errors in the frontend.
=> Improve error message handling

frontend/src/app/auth/auth-redirect/auth-redirect.component.ts, frontend/src/app/auth/http-interceptor/auth.interceptor.ts, frontend/src/app/header/header.component.html, frontend/src/app/header/header.component.ts, frontend/src/app/services/auth/auth.service.ts, frontend/src/app/services/user/user.service.ts, frontend/src/app/session-created/guacamole/guacamole.component.html, frontend/src/app/session-created/guacamole/guacamole.component.ts, frontend/src/app/settings/admin-settings/admin-user-settings/admin-user-settings.component.html, frontend/src/app/settings/repository-manager-settings/repository-settings/repository-user-settings/repository-user-settings.component.html, frontend/src/app/settings/settings.component.ts, frontend/src/app/settings/user-settings/user-settings.component.ts
* Consolidate all authentication related code in `AuthService`.
* Do no longer use local storage, except for development mode
TODO:
* Automatically redirect to authentication provider.
Resolves #107
... manual.
=> Improve OAuth2 functionality

backend/config/config_template.yaml, helm/config/backend.yaml, helm/values.yaml
There are some outdated references to model sources and backups in the backend configuration. This PR removes them.
=> Remove outdated backend configuration

frontend/src/app/projects/project-detail/project-users/project-user-settings.component.html, frontend/src/app/projects/project-overview/project-overview.component.css, frontend/src/app/projects/project-overview/project-overview.component.html, frontend/src/app/settings/modelsources/t4c-settings/create-t4c-instance/create-t4c-instance.component.html, frontend/src/app/settings/modelsources/t4c-settings/create-t4c-instance/create-t4c-instance.component.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.css, frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.html, frontend/src/styles.css
Apply the existing style to TeamForCapella instances to make them consistent with existing application.
=> Unique style for t4c instances

frontend/src/app/settings/settings.component.html
This PR improves accessibility by moving the routerLink attributes to anchors. `T4CSettings` component was ignored because another PR deals with it.
Resolves #121 
=> Button to anchors

.github/workflows/tests.yml, frontend/karma.conf.js
Adds a job to run the frontend karma tests in Github actions after each push.
=> Run frontend tests in Github Actions

frontend/src/app/app.component.css, frontend/src/app/general/footer/footer.component.css, frontend/src/app/general/metadata/version/version.component.css, frontend/src/app/general/metadata/version/version.component.html, frontend/src/app/general/metadata/version/version.component.ts, frontend/src/app/general/metadata/version/version.service.ts, frontend/src/styles.css
- Release notes don't show up anymore automatically.
- Instead, a new red text is shown if there is a new version. 
- The user can open the release notes dialog on request.
- This makes testing easier, because there is no dialog "randomly" showing up.
=> Release notes improvements

frontend/src/app/services/git/git.service.ts, frontend/src/app/services/model/model.service.ts, frontend/src/app/services/modelsources/git-model/git-model.service.ts, frontend/src/app/services/project/project.service.ts, frontend/src/app/services/settings/t4c-model.service.ts, frontend/src/app/services/tools/tool.service.ts
Related URLs are not supported by the URL object. Will switch back to strings.
=> Fix URL construction

frontend/package-lock.json, frontend/package.json, frontend/src/app/app.module.ts, frontend/src/app/helpers/skeleton-loaders/mat-card-overview-loader/mat-card-overview-loader.component.css, frontend/src/app/helpers/skeleton-loaders/mat-card-overview-loader/mat-card-overview-loader.component.html, frontend/src/app/helpers/skeleton-loaders/mat-card-overview-loader/mat-card-overview-loader.component.spec.ts, frontend/src/app/helpers/skeleton-loaders/mat-card-overview-loader/mat-card-overview-loader.component.ts, frontend/src/app/projects/project-overview/project-overview.component.css, frontend/src/app/projects/project-overview/project-overview.component.html, frontend/src/app/projects/project-overview/project-overview.component.ts
This PR changes the loading animation. The goal is to have a unified and consistent loading animation in the platform. There is general component that can be included in all components that use the mat-card-overview. More loading animations can be added in the future. 
Resolves #98
=> Add skeleton loader

.pre-commit-config.yaml, frontend/package-lock.json, frontend/src/app/app.module.ts
`isort` didn't pick up the configuration in the `pyproject.toml`. Therefore, we have to run `isort` in the backend subdirectory.
=> Fix isort pre-commit hook

frontend/src/app/projects/create-project/create-project.component.ts, frontend/src/app/projects/models/create-model-base/create-model-base.component.html, frontend/src/app/projects/models/create-model-base/create-model-base.component.ts, frontend/src/app/projects/project-overview/project-overview.component.ts, frontend/src/app/services/project/project.service.ts
=> Update resources in services instead of components

backend/capellacollab/projects/users/routes.py, backend/capellacollab/users/routes.py, frontend/src/app/settings/core/user-settings/user-settings.component.ts
Small addition to PR https://github.com/DSD-DBS/capella-collab-manager/pull/323
=> Small fix for PR #323

backend/capellacollab/projects/capellamodels/routes.py, backend/capellacollab/projects/routes.py, backend/capellacollab/sessions/routes.py, backend/capellacollab/settings/modelsources/git/routes.py, backend/capellacollab/settings/routes.py, backend/capellacollab/tools/routes.py, backend/capellacollab/users/routes.py
This PR fixes the project creation and in addition adjusts some role and project role verification.
=> Fix project creation and verification problems

frontend/src/app/projects/models/create-model-base/create-model-base.component.html, frontend/src/app/projects/models/create-model-base/create-model-base.component.ts
This fixes the problem that the model tool was not marked as required in the frontend. It also includes some code quality improvements.
=> Make model tool required

frontend/src/app/sessions/active-sessions/active-sessions.component.html
- Make sessions buttons (Terminate / Connect / Upload) consistent
- Rename "Reconnect" to "Connect"
=> Styling for active sessions

.gitignore, backend/capellacollab/alembic/versions/cf93aadf77d6_add_t4c_instances.py, backend/capellacollab/alembic/versions/e7a140389e22_update_databaset4cmodel_table.py, backend/capellacollab/alembic/versions/fdff657f3cc1_add_ocd_port_to_t4c_instance.py, backend/capellacollab/projects/capellamodels/modelsources/t4c/crud.py, backend/capellacollab/projects/capellamodels/modelsources/t4c/models.py, backend/capellacollab/projects/capellamodels/modelsources/t4c/routes.py, backend/capellacollab/settings/modelsources/t4c/models.py, frontend/src/app/projects/models/model-detail/model-detail.component.html, frontend/src/app/services/settings/t4c-instance.service.ts, frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html, frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
This PR add the CDO port to T4C Instances, and adjust some stuff with the port of the T4C Instances.
=> Add CDO port to T4C instances.

backend/capellacollab/alembic/versions/951433f1f092_move_models_to_own_table.py
Previously, we created one Capella model for each t4c model / git model. However, in v1 one "project" was comparable to the new Capella model. Therefore, it makes sense to create exactly one model per project and add all the git_models and t4c_models to the specific model.
=> Create only one model per project during migration

backend/capellacollab/alembic/versions/d6a23ac7f263_add_credentials_for_gitmodels.py, backend/capellacollab/core/database/migration.py, backend/capellacollab/projects/capellamodels/crud.py
…mpty string.
On tools creation, models now have a default tool. Also, the default value of git_models.username is set on empty string on migration.
=> Fix small migration issues

backend/capellacollab/projects/capellamodels/modelsources/t4c/routes.py, backend/capellacollab/settings/modelsources/git/core.py, frontend/src/app/services/modelsources/t4c-model/t4c-model.service.ts
=> Some bugfixes

backend/capellacollab/alembic/env.py, backend/capellacollab/core/database/migration.py
=> Set log level to correct one

backend/capellacollab/projects/capellamodels/crud.py, backend/capellacollab/projects/capellamodels/models.py, backend/capellacollab/projects/capellamodels/routes.py, frontend/src/app/projects/models/model-description/model-description.component.html, frontend/src/app/projects/models/model-description/model-description.component.ts, frontend/src/app/services/model/model.service.ts
=> Type and Nature are now editable in details.

.github/workflows/projects.yml
Please add a description of the changes. If the changes are in the frontend, please attach a screenshot.
If new dependencies are added, please briefly describe why they are needed.
Resolves #issue
=> Remove auto adding of pull requests to the Kanban board.

backend/capellacollab/notices/crud.py, backend/capellacollab/notices/models.py, backend/capellacollab/notices/routes.py, backend/tests/conftest.py, backend/tests/test_alerts.py
The deletion was not working anymore. This adds the bug fix and some tests to prevent misbehavior in the future.
=> Make deletion of alerts working again

backend/capellacollab/settings/modelsources/t4c/models.py, frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html, frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts
The title says all.
Resolves #408
=> Remove latin-1 validator

backend/capellacollab/__main__.py, backend/capellacollab/sessions/idletimeout.py, backend/tests/test_sessions_idletimeout.py, helm/templates/prometheus/prometheus.configmap.yaml, helm/values.yaml
Terminate idle sessions from the cluster.
It took a bit longer to get right. Created #434, which runs the cleanup job through a kubernetes cron job.
It seems to me this is the most appropriate solution at the moment: a simple timer and a cleanup job.
Resolves #76 
Live tested.
=> Terminate unused sessions

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/push.yml, .github/workflows/tests.yml
The previous tagging schema didn't work on default branches
=> Use own Docker tagging system

backend/capellacollab/alembic/versions/0ef0826d54e7_create_pure_variant_table.py, backend/capellacollab/routes/status.py, backend/capellacollab/sessions/operators/k8s.py, backend/capellacollab/sessions/routes.py, backend/capellacollab/settings/integrations/purevariants/crud.py, backend/capellacollab/settings/integrations/purevariants/models.py, backend/capellacollab/settings/integrations/purevariants/routes.py, docs/user/docs/sessions/reconnect.md, frontend/src/app/settings/integrations/pure-variants/pure-variants.component.css, frontend/src/app/settings/integrations/pure-variants/pure-variants.component.html, frontend/src/app/settings/integrations/pure-variants/pure-variants.component.ts, frontend/src/app/settings/integrations/pure-variants/service/pure-variants.service.ts
Upload a `pure::variants` license file in the settings. The license is stored as `Secret` in the underlying kubernetes cluster.
=> Upload `pure::variants` license in integration settings

backend/capellacollab/sessions/idletimeout.py, docs/user/docs/getting-started/capella-intro.md
Automatic session termination wasn't working anymore.
=> Switch Collab Manager session and database session

frontend/src/app/general/metadata/version/version.component.html, frontend/src/app/general/metadata/version/version.service.ts
=> Reset version when clicking on release notes

docs/user/docs/sessions/request.md
=> Terminate sessions docs

backend/capellacollab/sessions/routes.py, backend/tests/test_sessions_routes.py
Added comments unintentionally overwritten from #521.
=> Missed review comments

Makefile
So multiple capella versions can be built.
=> chore: quote capella-version var in makefile

.pre-commit-config.yaml, backend/capellacollab/core/database/migration.py, backend/capellacollab/projects/toolmodels/backups/crud.py, backend/capellacollab/projects/toolmodels/backups/models.py, backend/capellacollab/projects/toolmodels/backups/routes.py, backend/capellacollab/projects/toolmodels/modelsources/git/crud.py, backend/capellacollab/projects/toolmodels/modelsources/git/injectables.py, backend/capellacollab/projects/toolmodels/modelsources/git/models.py, backend/capellacollab/projects/toolmodels/modelsources/t4c/models.py, backend/capellacollab/sessions/models.py, backend/capellacollab/sessions/operators/k8s.py, backend/capellacollab/settings/modelsources/t4c/repositories/crud.py, backend/capellacollab/settings/modelsources/t4c/repositories/injectables.py, backend/tests/conftest.py, backend/tests/test_projects_routes.py, backend/tests/test_sessions_routes.py, backend/tests/toolmodels/conftest.py, backend/tests/toolmodels/test_pipelines.py
This PR fixes a bug that `pipelines` could not be loaded or created in the frontend. In addition, it adds several testcases for pipelines.
=> Fix loading and creation of backups

backend/capellacollab/sessions/operators/k8s.py
Resolves [#405](https://github.com/DSD-DBS/capella-collab-manager/issues/405)
=> fix assign correct cronjob reference

backend/Dockerfile, backend/capellacollab/__main__.py, backend/capellacollab/config/config_schema.yaml, backend/capellacollab/routes/status.py, backend/capellacollab/sessions/files/routes.py, backend/capellacollab/sessions/idletimeout.py, backend/capellacollab/sessions/operators/__init__.py, backend/capellacollab/sessions/operators/helper.py, backend/capellacollab/sessions/operators/k8s.py, backend/capellacollab/sessions/sessions.py, backend/tests/conftest.py, backend/tests/test_sessions_idletimeout.py, backend/tests/toolmodels/test_pipelines.py
Move the fileservice into the backend - Python code is executed via `kubectl exec`.
In addition, it fixes the upload & download of files.
=> Move the fileservice into the Collab Manager base

backend/capellacollab/sessions/operators/__init__.py, backend/capellacollab/sessions/operators/k8s.py
=> Load kubernetes config before initializing clients

guacamole/Dockerfile, helm/templates/guacamole/guacd.deployment.yaml, helm/values.yaml
Pin the version, to avoid future surprises.
=> Upgrade Guacamole to 1.5.0

backend/Dockerfile, frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/general/breadcrumbs/breadcrumbs.service.ts, frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.css, frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.html, frontend/src/app/projects/project-detail/edit-project-metadata/edit-project-metadata.component.ts, frontend/src/app/projects/project-detail/model-overview/model-overview.component.css, frontend/src/app/projects/project-detail/model-overview/model-overview.component.html, frontend/src/app/projects/project-detail/project-details.component.css, frontend/src/app/projects/project-detail/project-details.component.html, frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.css, frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.html, frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.ts, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.css, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.html, frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.css, frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.html, frontend/src/app/settings/core/user-settings/user-settings.component.html, frontend/src/app/settings/core/user-settings/user-settings.component.ts
Please check the commit messages for detailed information.
=> Redesign project detail page

frontend/src/app/projects/project-detail/project-details.component.css, frontend/src/app/projects/project-detail/project-details.component.html, frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.css, frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.html
=> Display project metadata and read-only sessions in one line

backend/capellacollab/projects/users/routes.py, frontend/src/app/general/header/header.component.css, frontend/src/app/general/header/header.component.html, frontend/src/app/general/header/header.component.ts, frontend/src/app/general/nav-bar/nav-bar.service.ts, frontend/src/app/projects/project-detail/model-overview/model-complexity-badge/model-complexity-badge.component.css, frontend/src/app/projects/project-detail/model-overview/model-complexity-badge/model-complexity-badge.component.html, frontend/src/app/projects/project-detail/model-overview/model-overview.component.css, frontend/src/app/projects/project-detail/model-overview/model-overview.component.html, frontend/src/app/projects/project-detail/project-details.component.html, frontend/src/app/projects/project-detail/project-metadata/project-metadata.component.html, frontend/src/app/projects/project-detail/project-users/add-user-to-project/add-user-to-project.component.html, frontend/src/app/projects/project-detail/project-users/add-user-to-project/add-user-to-project.component.ts, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.html, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.ts, frontend/src/app/projects/project-detail/project-users/service/project-user.service.ts, frontend/src/app/projects/project-wrapper/project-wrapper.component.ts, frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.css, frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.html, frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.ts
Loading of projects feels really slow in production and some calls in the frontend were done in wrappers instead of services.
The new loading animation: 
https://github.com/DSD-DBS/capella-collab-manager/assets/23395732/499630cd-ad15-4ec5-b500-4dbbd2182a56
=> Proper loading animations for project detail page

CONTRIBUTING.md, backend/capellacollab/__main__.py
This PR updates a few instructions for setting up the development environment.
Biggest change: 
- the option of setting up the OAuth Mock with a self signed certificate is removed
=> Update development instructions

backend/capellacollab/projects/toolmodels/models.py
=> Fix: Delete restriction during model deletion

backend/Makefile, backend/capellacollab/projects/toolmodels/backups/routes.py, backend/capellacollab/tools/crud.py, backend/capellacollab/tools/exceptions.py, backend/tests/conftest.py, frontend/src/app/projects/models/backup-settings/service/pipeline.service.ts, frontend/src/app/projects/models/backup-settings/trigger-pipeline/trigger-pipeline.component.html, frontend/src/app/projects/models/backup-settings/trigger-pipeline/trigger-pipeline.component.ts, frontend/src/app/settings/settings.component.ts
=> Fix: Properly handle backup creation and deletion errors

helm/templates/grafana/grafana.configmap.yaml, helm/templates/grafana/grafana.deployment.yaml
See https://github.com/grafana/grafana/issues/70110#issuecomment-1597403289
Resolves #827
=> Bump grafana version to 10.0.1

backend/capellacollab/core/database/migration.py, backend/capellacollab/projects/toolmodels/crud.py, backend/capellacollab/projects/toolmodels/models.py, backend/capellacollab/projects/toolmodels/routes.py, backend/capellacollab/sessions/crud.py, backend/capellacollab/sessions/models.py, backend/capellacollab/sessions/routes.py, backend/capellacollab/settings/modelsources/t4c/models.py, backend/capellacollab/settings/modelsources/t4c/repositories/crud.py, backend/capellacollab/tools/crud.py, backend/capellacollab/tools/injectables.py, backend/capellacollab/tools/integrations/models.py, backend/capellacollab/tools/integrations/routes.py, backend/capellacollab/tools/models.py, backend/capellacollab/tools/routes.py, backend/tests/projects/toolmodels/conftest.py, backend/tests/sessions/test_sessions_routes.py, backend/tests/settings/conftest.py, backend/tests/settings/test_t4c_instances.py
=> Refactor backend db names for Tool, Version, and Nature

backend/capellacollab/projects/events/__init__.py, backend/capellacollab/projects/events/crud.py, backend/capellacollab/projects/events/routes.py, backend/capellacollab/projects/injectables.py, backend/capellacollab/projects/models.py, backend/capellacollab/projects/routes.py, backend/capellacollab/projects/toolmodels/injectables.py, backend/capellacollab/projects/toolmodels/routes.py, backend/capellacollab/projects/users/routes.py, backend/capellacollab/sessions/routes.py, frontend/src/app/app.module.ts, frontend/src/app/events/events.component.ts, frontend/src/app/events/service/events.service.ts, frontend/src/app/projects/models/backup-settings/job-run-overview/job-run-overview.component.html, frontend/src/app/projects/project-detail/project-users/project-audit-log/project-audit-log.component.css, frontend/src/app/projects/project-detail/project-users/project-audit-log/project-audit-log.component.html, frontend/src/app/projects/project-detail/project-users/project-audit-log/project-audit-log.component.ts, frontend/src/app/projects/project-detail/project-users/project-audit-log/service/project-audit-log.service.ts, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.css, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.html, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.ts
=> Add audit log on project level

backend/capellacollab/projects/toolmodels/modelsources/git/exceptions.py, backend/capellacollab/projects/toolmodels/modelsources/git/github/handler.py, backend/capellacollab/projects/toolmodels/modelsources/git/handler/factory.py, docs/user/docs/projects/models/complexity_badge.md, docs/user/docs/projects/models/diagrams/setup_diagram_cache.md, docs/user/docs/projects/models/diagrams/view_diagram_cache.md, docs/user/docs/release-notes.md
Some minor changes as part of the review for #812.
=> chore: Suggestions for PR #812

backend/capellacollab/projects/toolmodels/modelbadge/routes.py, backend/capellacollab/projects/toolmodels/modelsources/git/github/handler.py, backend/capellacollab/projects/toolmodels/modelsources/git/gitlab/handler.py, backend/capellacollab/projects/toolmodels/modelsources/git/handler/handler.py, backend/tests/projects/toolmodels/conftest.py, backend/tests/projects/toolmodels/test_diagrams.py, backend/tests/projects/toolmodels/test_model_badge.py
=> feat: Get model badge from artifacts

docs/user/docs/projects/models/complexity_badge.md, docs/user/docs/projects/models/diagrams/setup_diagram_cache.md, docs/user/docs/settings/model-sources/git.md
fixes the last points of https://github.com/DSD-DBS/capella-collab-manager/issues/781
=> docs: Add github action documentation

docs/user/docs/sessions/files/files.md
=> fix(docs): Get adminition working

backend/capellacollab/sessions/files/routes.py, backend/startup.sh, frontend/src/app/sessions/user-sessions-wrapper/active-sessions/file-browser-dialog/file-browser-dialog.component.html
The '/' leads to temporary redirects.
=> fix: Remove '/' from files routes

backend/capellacollab/projects/toolmodels/routes.py
If a toolmodel had linked t4c or git repositories, the request return a success status even though nothing was deleted.
=> fix: Add backend validation for deps during model deletion

backend/capellacollab/projects/toolmodels/backups/routes.py, backend/capellacollab/projects/toolmodels/modelsources/git/injectables.py, backend/capellacollab/projects/toolmodels/modelsources/git/routes.py, backend/capellacollab/projects/toolmodels/modelsources/t4c/routes.py, backend/capellacollab/projects/toolmodels/routes.py, backend/capellacollab/settings/modelsources/git/routes.py, backend/capellacollab/settings/modelsources/t4c/repositories/interface.py
The Google style guide proposes module imports.
In this PR, some old-style imports are changed to the new style.
=> refactor: Change method and class import to module imports

backend/capellacollab/sessions/routes.py
This makes the request_persistent_session function a lot more lightweight.
Additionally, the check whether a session is a Jupyter session depends on
the activated Jupyter integration instead of the tool name now.
Should be merged after https://github.com/DSD-DBS/capella-collab-manager/pull/912 is merged.
=> refactor: Move conflicting persistent session check to method

.github/workflows/tests.yml, README.md
More information about Codecov: https://about.codecov.io/
=> ci: Add Codecov upload after pytest in GH action

docs/user/.readthedocs.yaml, docs/user/requirements.txt
More information about Read the docs:
https://docs.readthedocs.io/en/stable/index.html
=> docs: Add "Read the docs" configuration

frontend/src/app/sessions/service/session.service.ts
=> feat: Add handling for OpenShift event "AddedInterface"

backend/capellacollab/alembic/versions/d8cf851562cd_add_missing_empty_model_restrictions.py, backend/capellacollab/projects/toolmodels/crud.py, backend/capellacollab/projects/toolmodels/models.py, frontend/src/app/projects/models/model-restrictions/model-restrictions.component.ts, frontend/src/app/projects/models/model-restrictions/service/model-restrictions.service.ts
=> fix: Fix Setting Model Restrictions

frontend/src/app/app.component.html, frontend/src/app/app.component.ts, frontend/src/app/sessions/service/fullscreen.service.ts, frontend/src/app/sessions/session/session.component.css, frontend/src/app/sessions/session/session.component.html, frontend/src/app/sessions/session/session.component.ts
This PR introduces a fullscreen mode to enhance the user experience in the Session Viewer. The current layout utilizes significant space for the navbar and footer, which can be restrictive when using the Session Viewer. The fullscreen mode aims to provide more space by hiding the navbar and footer, allowing users to focus solely on their session.
Resolves #981 
Without fullscreen mode:
With fullscreen mode:
=> feat: Introduce Fullscreen Mode

docs/user/docs/sessions/request.md, docs/user/docs/sessions/types.md, docs/user/docs/sessions/types/persistent.md, docs/user/docs/sessions/types/read-only.md
=> Update read-only session related docs

frontend/src/app/app-routing.module.ts, frontend/src/app/settings/core/pipelines-overview/pipelines-overview.component.html
=> feat: Add hyperlinks in monitoring

frontend/src/app/app-routing.module.ts, frontend/src/app/app.module.ts, frontend/src/app/projects/models/create-model/create-model.component.html, frontend/src/app/projects/models/model-detail/model-detail.component.html, frontend/src/app/projects/models/model-source/choose-source.component.html, frontend/src/app/projects/models/model-source/t4c/create-t4c-model-new-repository/create-t4c-model-new-repository.component.css, frontend/src/app/projects/models/model-source/t4c/create-t4c-model-new-repository/create-t4c-model-new-repository.component.html, frontend/src/app/projects/models/model-source/t4c/create-t4c-model-new-repository/create-t4c-model-new-repository.component.ts
=> feat: Create t4c repository in t4c model creation

backend/capellacollab/projects/toolmodels/crud.py, backend/capellacollab/projects/toolmodels/models.py, backend/capellacollab/projects/toolmodels/routes.py, backend/tests/projects/toolmodels/test_toolmodel_routes.py, frontend/src/app/app.component.ts, frontend/src/app/projects/models/model-description/model-description.component.html, frontend/src/app/projects/models/model-description/model-description.component.ts, frontend/src/app/projects/models/service/model.service.ts
=> feat: Add possibility to update toolmodel name

.pre-commit-config.yaml, backend/capellacollab/cli/__init__.py, backend/capellacollab/cli/__main__.py, backend/capellacollab/cli/ws.py, backend/pyproject.toml, backend/tests/cli/test_ws.py, docs/docs/admin/cli.md, docs/mkdocs.yml
A little tool to back up workspaces.
```bash
python -m capellacollab.cli ws volumes --namespace collab-sessions
python -m capellacollab.cli ws ls  persistent-session-admin --namespace collab-sessions
python -m capellacollab.cli ws backup persistent-session-admin --namespace collab-sessions
python -m capellacollab.cli ws restore persistent-session-admin persistent-session-admin-backup.tar.gz --namespace collab-sessions
```
=> Workspace backup CLI tool

backend/capellacollab/projects/toolmodels/backups/runs/interface.py
=> fix: Ensure that loki labels are strings

backend/capellacollab/alembic/versions/0e2028f83156_add_user_determined_display_order_to_.py, backend/capellacollab/projects/toolmodels/crud.py, backend/capellacollab/projects/toolmodels/models.py, backend/capellacollab/projects/toolmodels/routes.py, backend/tests/projects/toolmodels/test_toolmodel_routes.py, frontend/package-lock.json, frontend/src/app/app.module.ts, frontend/src/app/projects/models/service/model.service.ts, frontend/src/app/projects/project-detail/model-overview/model-overview.component.html, frontend/src/app/projects/project-detail/model-overview/model-overview.component.ts, frontend/src/app/projects/project-detail/model-overview/reorder-models-dialog/reorder-models-dialog.component.html, frontend/src/app/projects/project-detail/model-overview/reorder-models-dialog/reorder-models-dialog.component.ts
Provides project managers a way to change the display order of models in a project overview for all team members. 
Resolves #809
=> feat: Add ability to reorder models in project overview

backend/capellacollab/settings/modelsources/t4c/repositories/routes.py, frontend/src/app/general/error-handling/error-handling.interceptor.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.component.html, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.component.ts
=> fix: Properly show T4C repo deletion warnings

frontend/src/app/settings/modelsources/git-settings/edit-git-settings/edit-git-settings.component.ts
=> fix: Properly set API url when editing Git instance settings

backend/capellacollab/alembic/versions/f55b41e32223_make_instance_name_unique.py, backend/capellacollab/core/database/models.py, backend/capellacollab/core/exceptions.py, backend/capellacollab/settings/modelsources/t4c/crud.py, backend/capellacollab/settings/modelsources/t4c/exceptions.py, backend/capellacollab/settings/modelsources/t4c/models.py, backend/capellacollab/settings/modelsources/t4c/routes.py, backend/tests/settings/test_t4c_instances.py, frontend/src/app/app-routing.module.ts, frontend/src/app/projects/models/model-source/t4c/manage-t4c-model/manage-t4c-model.component.ts, frontend/src/app/services/settings/t4c-instance.service.ts, frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html, frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-settings-wrapper/t4c-settings-wrapper.component.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-settings.component.ts
=> feat: Add T4C instance name validation

.pre-commit-config.yaml, frontend/src/app/projects/models/backup-settings/pipeline-runs/service/pipeline-run.service.ts, frontend/src/app/projects/models/diagrams/model-diagram-preview-dialog/model-diagram-preview-dialog.component.html, frontend/src/app/projects/project-detail/model-overview/model-detail/git-model.service.ts, frontend/src/app/projects/project-detail/model-overview/move-model/move-model.component.ts, frontend/src/app/projects/project-detail/project-users/project-audit-log/service/project-audit-log.service.ts, frontend/src/app/projects/project-detail/project-users/service/project-user.service.ts, frontend/src/app/services/settings/t4c-instance.service.ts, frontend/src/app/sessions/session/session-iframe/session-iframe.component.html, frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.ts, frontend/src/app/settings/modelsources/t4c-settings/service/t4c-repos/t4c-repo.service.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.html
I ran `pre-commit autoupdate`, updated two versions manually (they were pointing to alpha versions) and did `pre-commit run -a`.
=> build: Update `pre-commit` versions

backend/capellacollab/projects/toolmodels/backups/runs/interface.py, backend/capellacollab/projects/toolmodels/modelsources/git/validation.py
More info why bare-except shouldn't be used:
https://pylint.pycqa.org/en/latest/user_guide/messages/warning/bare-except.html
=> refactor: Remove usage of bare-except

README.md
=> docs: Add showcase video to README

Makefile
When running make deploy other targets which make use of rollout, wait for the rollout to finish before opening the frontend in the browser.
=> build(dev): Wait for rollout to finish

docs/docs/user/sessions/troubleshooting.md
Additionally, this commit contains information about wrong scaling of sessions.
=> docs: Add troubleshooting for long session request times

backend/capellacollab/core/logging/__init__.py
Dark blue was hard to read on some dark backgrounds. This commit changes all colors to bright colors.
=> feat: Improve readability of log messages

backend/capellacollab/core/database/migration.py, backend/capellacollab/sessions/operators/k8s.py, backend/capellacollab/settings/modelsources/t4c/models.py, backend/capellacollab/settings/modelsources/t4c/repositories/routes.py, backend/pyproject.toml, backend/tests/settings/teamforcapella/conftest.py
Copied from https://github.com/DSD-DBS/capella-collab-manager/pull/1461, but with main as target branch.
=> refactor: Enable pylints' invalid name rule C0103

.pre-commit-config.yaml, frontend/.eslintrc.js, frontend/.gitignore, frontend/.storybook/main.ts, frontend/.storybook/preview-head.html, frontend/.storybook/preview.ts, frontend/.storybook/tsconfig.doc.json, frontend/.storybook/tsconfig.doc.json.license, frontend/.storybook/tsconfig.json, frontend/.storybook/tsconfig.json.license, frontend/.storybook/typings.d.ts, frontend/Makefile, frontend/angular.json, frontend/package-lock.json, frontend/package.json, frontend/tsconfig.app.json
Storybook can be used to mock & test UI components. More information is available on their website:
https://storybook.js.org/
Resolves #1370
Depends on https://github.com/DSD-DBS/capella-collab-manager/pull/1475
=> feat: Add Storybook with Compodoc integration

docs/docs/admin/settings/model-sources/t4c.md, docs/docs/admin/settings/tools/pure_variants.md, docs/docs/admin/teamforcapella/project-management/index.md
The option was renamed in the frontend.
This matches the new format.
=> docs: Rename `Profile` to `Menu`

Makefile, frontend/angular.json, frontend/src/app/projects/project-detail/model-overview/model-complexity-badge/model-complexity-badge.component.html, frontend/src/app/projects/project-detail/model-overview/model-complexity-badge/model-complexity-badge.component.ts, frontend/src/environments/environment.storybook.ts
Make documentation links working in Storybook by adding a new Angular environment.
=> feat(storybook): Add Angular environment for Storybook

backend/capellacollab/sessions/routes.py, backend/capellacollab/sessions/util.py, backend/capellacollab/tools/models.py, backend/tests/sessions/test_session_environment.py
=> fix: Add two stages for environment variable resolution

frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-session-history/create-session-history.stories.ts
Otherwise, a change is detected in Chromatic after each build.
=> test: Use a fixed date for session history

frontend/src/app/settings/modelsources/git-settings/git-settings.component.ts, frontend/src/app/settings/modelsources/git-settings/git-settings.stories.ts
=> fix: NullInjectionError in Git instance settings

helm/config/grafana/active-sessions.json, helm/templates/grafana/grafana.deployment.yaml
Unfortunately, #1573 was merged in an incomplete state due to a missing push. This PR adds the missing changes so that the dashboard works as described in the PR.
=> fix(monitoring): Fetching of variables in "Active Sessions" dashboard

.pre-commit-config.yaml
=> ci: Add Gitleaks to pre-commit configuration

backend/tests/test_alembic.py
While running the backend tests, I kept getting an `IndexError' for retrieving the database container's external port for the init database test. This change now properly waits for the container to run. If the container is already running, the behavior is exactly the same as before, i.e. we only wait if the container is not already running.
=> refactor: Wait for database container to start for database init test

frontend/src/app/helpers/skeleton-loaders/mat-card-overview-skeleton-loader/mat-card-overview-skeleton-loader.component.css, frontend/src/app/helpers/skeleton-loaders/mat-card-overview-skeleton-loader/mat-card-overview-skeleton-loader.component.html, frontend/src/app/helpers/skeleton-loaders/mat-card-overview-skeleton-loader/mat-card-overview-skeleton-loader.component.ts, frontend/src/app/projects/project-overview/project-overview.component.css, frontend/src/app/projects/project-overview/project-overview.component.html, frontend/src/app/projects/project-overview/project-overview.component.ts, frontend/src/app/projects/project-overview/project-overview.stories.ts, frontend/src/storybook/project.ts
In addition, add stories for the projects overview and migrate to new code style
=> feat: Align projects with announcements

.github/workflows/storybook.yml
Show number of snapshots and count of changes in the Storybook comment.
=> ci: Add Storybook visual testing results to PR comment

docs/docs/admin/teamforcapella/migration.md
Thanks for reporting @Block124.
=> docs: Fix wrong link to connected users docs

.github/workflows/storybook.yml
Goal is to reduce the number of snapshots in chromatic.
=> ci: Skip Storybook build on draft PRs

frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.css, frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.ts, frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.stories.ts
Resolves number 2 of https://github.com/DSD-DBS/capella-collab-manager/issues/1739
=> feat: Allow renaming of T4C instances in the frontend

frontend/src/app/settings/modelsources/t4c-settings/edit-t4c-instance/edit-t4c-instance.component.html, frontend/src/app/settings/modelsources/t4c-settings/licences/licences.component.html, frontend/src/app/settings/modelsources/t4c-settings/service/t4c-repos/t4c-repo.service.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.html, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.docs.mdx, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.stories.ts
- Use a proper text for the status of the instance.
- Display the ID of the repository above the status icon.
- Added Stories for the T4C repository component
- Use the new Angular control flow
- And more...
=> feat: Redesign T4C Instance administrator view

.github/workflows/storybook-publish.yml
Chromatic UI review was replaced by reg-actions in this repository. We still use Chromatic for Storybook publishing.
=> ci: Disable Chromatic UI review

frontend/src/app/projects/service/project.service.ts
=> fix(frontend): Make project deletion working again

backend/capellacollab/__main__.py, backend/capellacollab/alembic/versions/7cf3357ddd7b_add_feedback_table.py, backend/capellacollab/core/database/models.py, backend/capellacollab/feedback/crud.py, backend/capellacollab/feedback/metrics.py, backend/capellacollab/feedback/models.py, backend/capellacollab/feedback/routes.py, backend/capellacollab/feedback/util.py, backend/capellacollab/settings/modelsources/t4c/metrics.py, backend/capellacollab/users/routes.py, backend/tests/conftest.py, backend/tests/projects/toolmodels/pipelines/pipeline-runs/test_pipeline_runs.py, backend/tests/test_feedback.py, helm/config/grafana/dashboards/active-sessions.json, helm/config/grafana/dashboards/feedback.json, helm/config/grafana/dashboards/feedback.json.license
=> feat(monitoring): Add Grafana dashboard for feedback

backend/capellacollab/config/models.py, backend/capellacollab/sessions/operators/k8s.py, helm/Makefile, helm/config/backend.yaml, helm/templates/backend/backend.deployment.yaml, helm/templates/backend/postgres.deployment.yaml, helm/templates/docs/docs.deployment.yaml, helm/templates/frontend/frontend.deployment.yaml, helm/templates/grafana/grafana.deployment.yaml, helm/templates/grafana/nginx.deployment.yaml, helm/templates/guacamole/guacamole.deployment.yaml, helm/templates/guacamole/guacd.deployment.yaml, helm/templates/guacamole/postgres.deployment.yaml, helm/templates/mock/oauth.deployment.yaml, helm/templates/mock/smtp.deployment.yaml, helm/templates/prometheus/nginx.deployment.yaml, helm/templates/sessions/sessions.deployment.yaml, helm/templates/tpl/_containerSpec.tpl, helm/templates/tpl/_podSpec.tpl, helm/values.yaml
The `nodeSelector` can be defined in the `values.yaml` for the session pods and the management portal pods individually.
=> feat: Add support for nodeSelector

backend/capellacollab/sessions/routes.py, backend/tests/sessions/test_session_hooks.py, frontend/src/app/openapi/api/sessions.service.ts, frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.stories.ts, frontend/src/app/sessions/delete-session-dialog/delete-session-dialog.component.ts, frontend/src/app/sessions/service/session.service.ts, frontend/src/app/sessions/session-overview/session-overview.component.html, frontend/src/app/sessions/session-overview/session-overview.component.ts, frontend/src/app/sessions/session-overview/session-overview.stories.ts, frontend/src/app/sessions/user-sessions-wrapper/active-sessions/active-sessions.stories.ts, frontend/src/app/sessions/user-sessions-wrapper/create-session/create-readonly-session/create-readonly-session.component.ts, frontend/src/storybook/session.ts
The loading and "no sessions" cases are now handled separately.
=> feat: Add better edge case handling in session viewer

frontend/src/app/projects/models/model-source/git/manage-git-model/manage-git-model.component.ts
Add `resultUrlPrefixAsyncValidator` again. Was removed in https://github.com/DSD-DBS/capella-collab-manager/pull/1838
=> fix: Git component form fields aren't activated properly

docs/docs/development/frontend/testing.md, docs/docs/development/index.md, frontend/.browserslistrc, frontend/src/polyfills.ts
=> docs: Update links from angular.io to angular.dev

frontend/src/app/projects/create-project/create-project.stories.ts
We have to give it a bit more time to wait for the play function to finish.
=> test(storybook): Capture "Create project" story snapshots with delay

backend/capellacollab/settings/modelsources/t4c/license_server/models.py, backend/capellacollab/settings/modelsources/t4c/license_server/routes.py, backend/capellacollab/settings/modelsources/t4c/routes.py, backend/tests/settings/teamforcapella/test_t4c_license_servers.py, frontend/src/app/openapi/api/settings-modelsources-t4-c-license-servers.service.ts, frontend/src/app/sessions/license-indicator/license-indicator.component.html, frontend/src/app/sessions/license-indicator/license-indicator.component.ts, frontend/src/app/sessions/license-indicator/license-indicator.stories.ts, frontend/src/app/sessions/license-indicator/license-usage.service.ts, frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.html, frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.component.ts, frontend/src/app/sessions/user-sessions-wrapper/create-sessions/create-persistent-session/create-persistent-session.stories.ts
=> feat: Add indicator to warn when most T4C licenses are being used

backend/capellacollab/projects/models.py, backend/capellacollab/projects/toolmodels/exceptions.py, backend/capellacollab/projects/toolmodels/routes.py, backend/capellacollab/tools/models.py, backend/tests/projects/fixtures.py, backend/tests/projects/toolmodels/test_toolmodel_routes.py, backend/tests/tools/test_tools_routes.py, frontend/src/app/openapi/model/tool-session-configuration-input.ts, frontend/src/app/openapi/model/tool-session-configuration-output.ts, frontend/src/app/projects/models/create-model-base/create-model-base.component.html, frontend/src/app/projects/models/create-model-base/create-model-base.component.ts, frontend/src/storybook/tool.ts
=> feat: Allow setting support project types for tools

backend/capellacollab/sessions/hooks/log_collector.py, backend/capellacollab/tools/models.py, backend/capellacollab/tools/routes.py, frontend/src/app/openapi/.openapi-generator/FILES, frontend/src/app/openapi/model/logging-configuration-input.ts, frontend/src/app/openapi/model/logging-configuration-output.ts, frontend/src/app/openapi/model/models.ts, frontend/src/app/openapi/model/session-monitoring-output.ts, frontend/src/storybook/tool.ts
=> feat: Add custom promtail / logging configuration for tools

docs/mkdocs.yml, docs/requirements.txt
- Add lightbox for images
- Add dark mode
- Add SPA mode and link prefetching
Closes #2005
=> feat: Add dark mode and lightbox for docs

frontend/src/app/projects/models/diagrams/model-diagram-dialog/model-diagram-code-block/model-diagram-code-block.stories.ts, frontend/src/app/users/users-profile/common-projects/common-projects.component.html
In addition, add a path to the diagram cache stories.
=> chore: Improve word wrapping of common projects

frontend/.storybook/main.ts, frontend/.storybook/preview.ts, frontend/.storybook/tsconfig.json, frontend/angular.json, frontend/package.json
- Disable Compodoc, it wasn't used
=> perf: Speed up Storybook start time

helm/config/grafana/dashboards/active-sessions.json
=> feat(metrics): Count all sessions and session minutes over time range

docs/docs/admin/teamforcapella/project-management/index.md
Just improve the language a bit.
=> docs: Improve language a bit

frontend/src/app/general/relative-time/relative-time.component.html, frontend/src/app/general/relative-time/relative-time.component.ts, frontend/src/app/sessions/session-overview/session-overview.component.html
In addition, add support for custom date formats for increased flexibility.
=> feat: Underline relative-times to indicate possibility of hovering

frontend/src/app/sessions/session/session-viewer.service.ts
=> feat: Add communication with training mode to auto-fullscreen windows

frontend/nginx.conf
=> build: Use gzip

backend/capellacollab/metrics.py, backend/capellacollab/users/crud.py, backend/capellacollab/users/metrics.py, backend/tests/users/test_users.py, helm/config/grafana/dashboards/users.json, helm/config/grafana/dashboards/users.json.license
This solves the users part of #2099 but doesn't add the feedback-related features.
=> feat: Add a dashboard to show users to grafana

helm/config/grafana/dashboards/active-sessions.json
=> feat(monitoring): Show Xpra latency in Grafana

.github/workflows/bundle-analysis.yml, frontend/package.json, frontend/pnpm-lock.yaml, frontend/vite.config.ts
=> feat: Add bundle size analysis powered by codecov

backend/capellacollab/sessions/hooks/log_collector.py
Enable log filtering by specific session ID.
=> feat: Add session_id as label to session logs

frontend/src/app/settings/integrations/pure-variants/pure-variants.component.html, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.css, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-instance-settings.component.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.component.css, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.component.html, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.component.ts, frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.stories.ts
=> chore: Update Delete Repo Dialog to use modern Angular Control Flow

backend/capellacollab/sessions/hooks/guacamole.py, backend/pyproject.toml, backend/tests/sessions/hooks/test_guacamole_hook.py, backend/tests/sessions/test_session_hooks.py
=> chore: Enable pep8-naming ruff rule (N)

frontend/src/app/settings/modelsources/t4c-settings/t4c-instance-settings/t4c-repo-deletion-dialog/t4c-repo-deletion-dialog.component.html
This sometimes produces a diff in Storybook.
=> chore: Disable spellcheck in TeamForCapella deletion dialog

backend/capellacollab/alembic/versions/db35c7cfb407_add_managed_field_to_personal_access_.py, backend/capellacollab/permissions/models.py, backend/capellacollab/sessions/hooks/session_token.py, backend/capellacollab/users/models.py, backend/capellacollab/users/tokens/crud.py, backend/capellacollab/users/tokens/exceptions.py, backend/capellacollab/users/tokens/injectables.py, backend/capellacollab/users/tokens/models.py, backend/capellacollab/users/tokens/routes.py, backend/tests/users/test_tokens.py, frontend/src/app/openapi/model/admin-scopes-input.ts, frontend/src/app/openapi/model/admin-scopes-output.ts, frontend/src/app/openapi/model/user-token-with-password.ts, frontend/src/app/openapi/model/user-token.ts, frontend/src/app/users/personal-access-tokens/personal-access-tokens.component.html, frontend/src/app/users/personal-access-tokens/personal-access-tokens.component.ts, frontend/src/app/users/personal-access-tokens/personal-access-tokens.stories.ts
Managed tokens can only be revoked by administrators.
=> feat: Mark session tokens as managed

frontend/src/app/projects/create-project/create-project.component.html, frontend/src/app/projects/create-project/create-project.component.ts, frontend/src/app/projects/models/backup-settings/create-backup/create-backup.component.html, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.html, frontend/src/app/projects/project-detail/project-users/project-user-settings.component.ts, frontend/src/app/projects/project-detail/project-users/project-user-settings.stories.ts, frontend/src/app/projects/project-detail/project-users/service/project-user.service.ts
A project user shouldn't see the action to remove himself.
=> fix: Do show actions for own project user

frontend/src/app/general/auth/auth-redirect/auth-redirect.component.css, frontend/src/app/general/auth/auth-redirect/auth-redirect.component.html, frontend/src/app/general/auth/auth-redirect/auth-redirect.component.ts, frontend/src/app/general/auth/auth-redirect/auth-redirect.stories.ts, frontend/src/app/users/add-tags-dialog/add-tags-dialog.stories.ts
=> feat: Replace auth redirect message with spinner

.github/workflows/docs.yml, backend/capellacollab/__main__.py, docs/docs/api/index.md, docs/docs/api/redirect/openapi.md, docs/docs/api/redirect/redoc.md, docs/docs/api/redirect/swagger.md, docs/mkdocs.yml, helm/templates/routing/routing.ingress.yaml
=> fix: Rewire API docs redirect
